### ISSUE TITLE
Migrate from libtgvoip to tgcalls

### ISSUE THREAD

**Issue by vkryl** [TGX-Android/Telegram-X#134]
`libtgvoip` is obsolete is no longer used in other clients. It must be replaced with `tgcalls`.

Should be designed as a completely separate submodule similar to `x-core`, `tdlib` and other ones located [in this folder](/TGX-Android/Telegram-X/tree/main/vkryl) and included in this project as a git submodule.

**Comment by FuzzyQuills** [comment]
Is this why I couldn't make a test call from Telegram X to the stock TG client? (Gets stuck exchanging encryption keys on the stock android app end, while TGX has apparently successfully connected, but there's no audio)

**Comment by Whitebrim** [comment]
> Gets stuck exchanging encryption keys on the stock android app end, while TGX has apparently successfully connected, but there's no audio

Same for me

**Comment by Wayne2l** [comment]
Hi guys am really facing an issue on this TG

**Comment by terrytw** [comment]
Just curious, whether switching to tgcalls means that tgx will get video call function?

**Comment by oksakhartman** [comment]
@vkryl 

now calls on ios not work 

coz ios client droped libtgvoip
