### ISSUE TITLE
🏆 Telegram X Android Competition: Round 1. Reactions

### ISSUE THREAD

**Issue by vkryl** [TGX-Android/Telegram-X#154]
# 🏆 Telegram X Android Competition: Round 1. Reactions

**Prize fund for Round 1**: $25,000. 
**Deadline**: 23:59 on July 2nd (Dubai time). 
**Who can participate**: Everyone. 
**Results announcement**: July 12th, 2022. 

**The Task** is to implement message reactions identical to the demo materials of `TGX Reactions.zip` attached below, including all the animations, layouts, and other visual effects:

* You should use the Telegram X code (https://github.com/TGX-Android/Telegram-X) available on GitHub.
* You must avoid using existing codebase of the same functionality from other Telegram clients.
* Final result must be submitted as the ready-to-merge pull request to this repository on the deadline date.

**Your pull request should support:**

1. Sending a reaction to each message type in private chats, groups, and channels. When holding down an emoji in the reactions panel, the app is expected to display a full-screen animation effect once the reaction is sent. 
2. Allowing a user to set their preferred Quick Reaction in Settings.
3. Accessing the list of reacted users in groups in the following ways:
• Press and hold the specific reaction button for a quick view.
• Open the 'Reacted' list to show a multi-tab interface, with individual sections for each reaction emoji. Users should be able to switch tabs via a swipe gesture.
4. Turning message reactions on or off in group and channel management – including the ability for admins to disable and enable individual reaction emoji from the list.
5. Display an unseen reaction badge both in the chat list and inside the conversation.

**Evaluation Criteria:**

1. The overall code quality will be a top priority, aside animations smoothness and overall stability. Make sure to get familiar with the project structure and [guide for contributors](https://github.com/TGX-Android/Telegram-X/blob/main/docs/GUIDE.md) before getting started. Reactions code should keep in mind possible future use on other screens outside of the task (i.e. placing reactions through shared media).
2. The implemented features should not impact existing functions, like causing the app to crash when interacting with other features.
3. Ensure the app is free of major glitches, interface jumps, and severe layout issues.
4. Your app should run smoothly on a wide range of devices. In the evaluation stage, we will test with several devices, including Samsung Galaxy (A51, S10, S21 Ultra), Xiaomi Redmi Note 8 Pro, and more.
5. Implementing a *clearly* better stickers rendering (i.e. less disk space usage, better FPS, less CPU usage) will be considered a major advantage, but only in case of completing all other parts of the task.
6. Attempts to impersonate someone else's work (i.e. submitting a copy of someone else's pull request) would lead to permanent disqualification from Telegram X contests and any potential reward systems in future.

**Submissions:**

Contestants will be able to submit their entries to [@ContestBot](https://t.me/ContestBot) at the end of this round. We will further clarify the submission instructions closer to the deadline.

*P.S. For the next stage, we expect to only invite contestants who achieved 🥉 3rd place or higher in this round.*

***

**Contents of `TGX Reactions.zip`:**

<details>
<summary><b>Designs (41 images)</b></summary>

![Reactions 0 0 - Bubbles](https://user-images.githubusercontent.com/6242627/173208591-3d1522fa-61be-480c-87fe-233f9fac0b08.png)
![Reactions 0 1 - Flat](https://user-images.githubusercontent.com/6242627/173208593-9488ab0c-2f7c-4240-82c5-c3f315e4dfff.png)
![Reactions 1 0 - Message](https://user-images.githubusercontent.com/6242627/173208596-9c4cc7dd-d4ef-4e02-9fe3-f566faa48188.png)
![Reactions 1 1 - Media](https://user-images.githubusercontent.com/6242627/173208598-f1be3e1d-6c21-46df-8073-c859869d0a68.png)
![Reactions 1 2 - Sticker](https://user-images.githubusercontent.com/6242627/173208601-9665ce24-0aed-428b-a37e-bb7904b10ca9.png)
![Reactions 1 3 - Rounded Video](https://user-images.githubusercontent.com/6242627/173208604-2d9a0197-7e1f-4fa4-8049-1b4d750ab1cc.png)
![Reactions 1 4 - Multiple](https://user-images.githubusercontent.com/6242627/173208605-c746d2f1-a279-44c3-9569-eeaf381c813b.png)
![Reactions 2 0 - Message](https://user-images.githubusercontent.com/6242627/173208606-b2ae23a4-baa5-4bd3-873b-a933e70b45d1.png)
![Reactions 2 1 - Media](https://user-images.githubusercontent.com/6242627/173208607-aeae12b6-3af7-4330-a027-0bfbeaafd696.png)
![Reactions 2 2 - Sticker](https://user-images.githubusercontent.com/6242627/173208608-35a17fe0-4946-4edf-93e3-d0b206380a40.png)
![Reactions 2 3 - Rounded Video](https://user-images.githubusercontent.com/6242627/173208610-57686501-96eb-473d-86d5-fe4f6c650e4e.png)
![Reactions 2 4 - Multiple](https://user-images.githubusercontent.com/6242627/173208612-28810472-55e7-444f-9eb4-78cff3cfe12d.png)
![Reactions 3 0 - Reaction bar](https://user-images.githubusercontent.com/6242627/173208613-5a126018-dac1-49d9-b363-1bbf0e590d0e.png)
![Reactions 3 1 - Reaction bar with counter](https://user-images.githubusercontent.com/6242627/173208614-296f4d26-a547-4365-a8ee-d9c60db95f19.png)
![Reactions 3 2 - Reacted](https://user-images.githubusercontent.com/6242627/173208616-33a4ecfe-44fe-4283-b2bb-b426ac678c32.png)
![Reactions 3 3 - Reaction bar with seen counter](https://user-images.githubusercontent.com/6242627/173208618-3dac6743-9d98-44dd-a1f8-e9e77a7487b4.png)
![Reactions 3 4 - All reacted](https://user-images.githubusercontent.com/6242627/173208619-32d7bd6a-21c7-4912-9c17-e6c258d35006.png)
![Reactions 3 5 - Single reaction](https://user-images.githubusercontent.com/6242627/173208621-d360894d-f566-4cb3-8c40-bd84cd18886a.png)
![Reactions 3 6 - Expanded](https://user-images.githubusercontent.com/6242627/173208624-cbe3e26b-2fe3-46ed-b7d1-9bf081f94af4.png)
![Reactions 3 7 - Seen](https://user-images.githubusercontent.com/6242627/173208625-e3cf8c52-bac6-411d-ae52-2fb19d780dde.png)
![Reactions 3 8 - Long pressed on reaction](https://user-images.githubusercontent.com/6242627/173208627-321b90c4-928b-4dbb-88f9-82c8584974eb.png)
![Reactions 4 0 - Reaction Notification Badge](https://user-images.githubusercontent.com/6242627/173208628-cc2d2f9a-3090-48eb-bd87-b3b45ef12bbe.png)
![Reactions 4 1 - Reaction Notification Badge with unread](https://user-images.githubusercontent.com/6242627/173208629-e231a175-a5a8-4f4d-8afc-d935d2125b6f.png)
![Reactions 4 2 - Reaction Notification Badge with unread and mention](https://user-images.githubusercontent.com/6242627/173208631-042a386b-f2d7-400c-8731-6f2ab708b4fe.png)
![Reactions 5 0 - Quick Reaction option](https://user-images.githubusercontent.com/6242627/173208633-0fccb9d1-1ddb-407c-a989-3e638800dc88.png)
![Reactions 5 1 - Selection](https://user-images.githubusercontent.com/6242627/173208635-1f7cf3eb-a174-40c2-97fb-cb06299f33ec.png)
![Reactions 5 2 - Reactions option](https://user-images.githubusercontent.com/6242627/173208636-1cb4131a-6ba2-4146-8ce6-6a31c5652a82.png)
![Reactions 5 3 - All disabled](https://user-images.githubusercontent.com/6242627/173208637-08d4e786-9aae-4b83-82d0-b9c3f5977009.png)
![Reactions 5 4 - Some enabled](https://user-images.githubusercontent.com/6242627/173208638-a607a614-8813-4f94-9fda-eff3dd3dec58.png)
![Reactions 5 5 - All enabled](https://user-images.githubusercontent.com/6242627/173208639-701e0969-08e5-4341-893b-b147fe9d601c.png)
![Reactions 6 0 - Big Reactions option](https://user-images.githubusercontent.com/6242627/173208640-4132b084-4c38-4f62-a182-9882c4dbf579.png)
![Reactions 6 1 - Selection](https://user-images.githubusercontent.com/6242627/173208641-939675ab-fd1e-47e3-bb8f-72d02869f22e.png)
![Reactions 7 0 - Wide Bubble](https://user-images.githubusercontent.com/6242627/173208642-698a6194-f09f-4000-8ef1-51eeb5171088.png)
![Reactions 7 1 - Narrow Bubble](https://user-images.githubusercontent.com/6242627/173208644-10feb8df-a900-4ca3-a026-66699e0a3d0f.png)
![Reactions 7 2 - Bubble with Big Reactions disabled](https://user-images.githubusercontent.com/6242627/173208645-3d673bf2-9451-42f9-9fb8-18348db3c922.png)
![Reactions 7 3 - Flat with Big Reactions disabled](https://user-images.githubusercontent.com/6242627/173208646-320ba81c-44e0-4902-b938-30a4a098dbff.png)
![Reactions 7 4 - Media Bubble](https://user-images.githubusercontent.com/6242627/173208648-46fd189e-0184-4688-9088-c4829ebb28d0.png)
![Reactions 7 5 - Sticker and Emoji](https://user-images.githubusercontent.com/6242627/173208656-64ce8c2c-39e8-41b5-ae92-6eb27efdc41c.png)
![Reactions 7 6 - Quick Reaction Bubble](https://user-images.githubusercontent.com/6242627/173208658-0333e65f-ddf6-41c8-8c02-162b1fa30f2f.png)
![Reactions 7 7 - Quick Reaction Flat](https://user-images.githubusercontent.com/6242627/173208659-dfceecd0-1bc0-4628-a20a-62712bc75420.png)
![Reactions 7 8 - Chatlist Badge](https://user-images.githubusercontent.com/6242627/173208661-18c4cafd-4717-48ff-8ec6-fcef778aca99.png)
</details>

<details>
<summary><b>Videos (5 files)</b></summary>

https://user-images.githubusercontent.com/6242627/173208712-b4397c62-9ab7-429a-8f07-5df87bf73c1c.mp4

https://user-images.githubusercontent.com/6242627/173208723-305c692a-c898-4826-951a-ad7b22a55abf.mov

https://user-images.githubusercontent.com/6242627/173208727-0aae66c9-5fbc-4649-ac62-f6a923994645.mp4

https://user-images.githubusercontent.com/6242627/173208730-b0b5ca23-2e14-4874-abf2-6cae1013e12a.mp4

https://user-images.githubusercontent.com/6242627/173208732-8137c125-2f97-4dbf-9bbe-3bf5b5a822c2.mp4

</details>

**Comment by vkryl** [comment]
Developers wishing to discuss the task and potential implementations are welcome to join https://t.me/tgx_dev chat.

P.S. Whoever else wishing to contribute Telegram X is welcome too.

**Comment by DavertMik** [comment]
I use telegram X instead of official client for one reason. It doesnt have reactions which are really really annoying and they cant be turned off. Please don't ruin telegram X.

**Comment by Scrxtchy** [comment]
> If you add them to client, please leave am option to disable them.

If one does not exist you may add this feature yourself

**Comment by PXNX** [comment]
Why isn't this client written in Kotlin? Makes code a bit nicer to read, gets rid of most NPEs und has somesyntactic sugar :)

**Comment by F1irSti** [comment]
And the developers of Telegram X do not want to add to their application the function of changing the storage location of files (from ROM to sd card)? How long will the users of this application wait for the addition of a feature that has been in regular Telegram for a long time? Or have you decided that users are not even worthy of such a feature?

**Comment by vkryl** [comment]
> Why isn't this client written in Kotlin? Makes code a bit nicer to read, gets rid of most NPEs und has somesyntactic sugar :)

Telegram X was created around 2014-2015, several years before Google announced first-class support for Kotlin. Telegram X uses Kotlin for some recent code though, e.g.: https://github.com/TGX-Android/Telegram-X/tree/main/vkryl

**Comment by vkryl** [comment]
Whoever participating in the contest, make sure to not miss implementation suggestions in https://t.me/tgx_dev that will be posted with `#contest` hashtag.

They will not be the requirement in any kind – just suggestions that might help getting the idea and plan on completing some parts of the contest task.

**Comment by vkryl** [comment]
Icons required by the mockups are [baseline_favorite](https://github.com/TGX-Android/Telegram-X/blob/main/app/src/main/res/drawable/baseline_favorite_20.xml) and [baseline_visibility](https://github.com/TGX-Android/Telegram-X/blob/main/app/src/main/res/drawable/baseline_visibility_24.xml) in `20` and `24` dpi available in the Telegram X source code. If you are not sure whether it's `20` or `24` on the specific mockup, ask in the [group](https://t.me/tgx_dev) (make sure to check if anyone else already asked about the same mockup).

To create an icon in the missing dimension just create a copy, edit `android:width` and `android:width` and file name suffix to match the desired dpi.

Circular checkbox is [SimplestCheckBox](https://github.com/TGX-Android/Telegram-X/blob/main/app/src/main/java/org/thunderdog/challegram/widget/SimplestCheckBox.java) — used in most parts of the app and you may find a lot of samples by checking out its usages.

For rectangular checkbox you would need a [CheckBoxView](https://github.com/TGX-Android/Telegram-X/blob/main/app/src/main/java/org/thunderdog/challegram/widget/SimplestCheckBox.java). You most likely do not need to create it directly, but to use [TYPE_CHECKBOX_OPTION](https://github.com/TGX-Android/Telegram-X/blob/main/app/src/main/java/org/thunderdog/challegram/ui/ListItem.java) item (check out its usages in the app for examples). Such item should be passed to `SettingsAdapter` instance (most commonly used by `RecyclerViewController`).

However, patching `CheckBoxView` (`onDraw` method specifically) would still be required in order to support an intermediate state needed by one of the mockups — state when checkbox mark angle increases from 90 to 180 degrees.

**Comment by vkryl** [comment]
Some clarification on a grid reactions selector screen.

**Behavior of the reactions settings from manage chat screen:**

1. When enabling some reaction by tap on the corresponding reaction, the overlay animation should play, the same one as in messages.
2. When all reactions are selected, checkbox should be in ✅  state
3. When some are not selected, it should be in ➖  state
4. When none, it should be empty 
5. When checkbox is at ✅  or ➖ state, it should unselect all reactions 
6. Otherwise it should select all reactions

**Behavior of quick reactions screen:**

1. Same as #1 in the previous section
2. By default only 👍 quick reaction is enabled
3. The limit of available quick reactions is determined by developer.
4. When trying to enable some quick reaction over reasonable limit (the amount at which point accessing it with gesture would become inconvenient or impossible), app should show the tooltip above it that limit reached.
5. Enabling / disabling quick reactions should preserve the previously selected reactions, but exact behavior details are up to the developer

Below some additional animations examples for better understanding of the screens and intended animations.

[TGX_AdditionalVideos.zip](https://github.com/TGX-Android/Telegram-X/files/8965141/TGX_AdditionalVideos.zip)

_Copy from https://t.me/tgx_dev/807_

**Comment by vkryl** [comment]
Submissions are closed and judges are now evaluating the results.

Here's the list of 11 participants: #188, #187, #180, #177, #182, #184, #179, #186, #183, #189, #185.

All APKs can be found in this channel: https://t.me/tgx_prs/148. Everyone is welcome to leave feedback and bug reports to developers inside of corresponding PR.

**Comment by grishka** [comment]
There will be no contest.com pages for this particular contest, right?

**Comment by vkryl** [comment]
> There will be no contest.com pages for this particular contest, right?

Soon they will be available there too.

**Comment by PXNX** [comment]
> There will be no contest.com pages for this particular contest, right?

There is: https://contest.com/android-x-r1

**Comment by Sonofjoy** [comment]
I think is nice so we should keep calm and carry on

**Comment by vkryl** [comment]
Check out the results for the first round: **[🏆 Telegram X Android Competition, Round 1 Results](https://t.me/contest/297)**

Keeping this issue open until the 1st place will be determined.

**Comment by seik0ixtem** [comment]
can't see from discussion - can reactions be fully disabled on client on winner's PR?

it's the most annoying feature ever existed in telegram and i'm choosing alt clients where it can be disabled.

**Comment by vkryl** [comment]
Thanks everyone who participated in this contest.

PR #185 was chosen to be rolled out to users and merged in 9224e8b commit. Wanted to also note #183 who did a great job implementing 60fps reactions playback and better reaction animation curve ("fly out" and "land" animation), which can be tested in this APK: https://t.me/tgx_prs/297.

The main reasons #185 was chosen over #183 is that it implemented animations fully (such as animating all bubble width and height changes when reaction is set or unset, better buttons sorting, etc), had less frame drops and freezes on low-end devices (especially in channels with extensive amount of reactions set) and didn't override much of app's basic components only for the code style preferences (which is just an addition to the previous points, but not the key reason why it was chosen).

Follow https://t.me/contest for the final result announcement and any new upcoming contests.
