### ISSUE TITLE
Bad experience with full screen media

### ISSUE THREAD

**Issue by sepehr-brj** [TGX-Android/Telegram-X#156]
Tgx UI doesn't play nicely with the status bar, notch and navigation bar, and this becomes really annoying when playing full screen media:
![Screenshot_20220617-105830_1](https://user-images.githubusercontent.com/55192376/174395183-ea9f51a8-c1da-441c-b3ba-474e1c19d246.png)

It'd be nice to add an option to show/hide the notch in full screen media:
![Screenshot_20220617-105857_1](https://user-images.githubusercontent.com/55192376/174395374-a94d7654-ce31-4b53-a6dc-1bde10130ce7.png)

Telegram X 0.24.9.1530-arm64-v8a
Nokia 5.4
Android 11

**Comment by TadiT7** [comment]
Note for the dev:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES (for cutouts)
https://developer.android.com/reference/android/view/WindowManager.LayoutParams#LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS (for cutouts and curved displays)

**Comment by vkryl** [comment]
Cutout mode is not relevant to the described issue.

**Comment by vkryl** [comment]
62f4dabf commit resolves this issue. Not in the best way, but at least now there is complete full-screen mode available.
