### ISSUE TITLE
Scroll bar in chat view - obnoxiously distracting and unthemable/unhideable

### ISSUE THREAD

**Issue by SaphireLattice** [TGX-Android/Telegram-X#159]
Just updated to the new version and congrats on finally going open source! 

But uh, I'm pretty sure that the scroll bar when opening a chat view was not there before, or it was much less noticeable? And I tried to theme it away and the theme setting just doesn't affect it at all

**Comment by vkryl** [comment]
Bug report doesn't include information necessary to investigate the issue.

**Comment by SaphireLattice** [comment]
Okay, that's fair, except that I have not found any info about what is necessary to be included in an issue within a README.md where I would expect it to be, hence the rather freeform reporting format.

Version: Telegram X 0.24.9.1530-arm64-v8a (a0dc1b0d) - installed via Google Play
Android: Android Pie (28)
Phone: Planet Cosmo_Communicator (Cosmo-9.0-Planet-02032021-V25)

**Comment by vkryl** [comment]
Guide for issues will be added soon. Thanks for the report details, but at least screenshot would be needed (preferably with the comparison to the previous one). There were changes, but certainly not to the scroll bar. At least not intentionally — it seems it didn't affect the majority of the devices.
