### ISSUE TITLE
Which version of TDlib has been used?

### ISSUE THREAD

**Issue by rexi1r** [TGX-Android/Telegram-X#161]
HI, I want to implement account.resetPassword but I don't know which version of tdlib has been used.

**Comment by vkryl** [comment]
The version currently used as of 6ecb522 is https://github.com/tdlib/td/commit/492a84d52b85a14777cdfe7979d7798cca019d0b

**Comment by vkryl** [comment]
In all last builds it's possible to check current TDLib commit used in the app (and therefore its version) by pressing `Settings — View Source Code — TDLib`.
