### ISSUE TITLE
Telegram x unaccessible for blind users

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [TGX-Android/Telegram-X#165]
Hello. I blind user and android developer. Telegram x almost unaccessible for blind users. Do you plan improve accessibility of telegram x,or it not interesting for you? Official telegram for android accessible for us,blind users,though it have accessibility problems too,but telegram x almost fully unaccessible for blind. I can only authorize in it,and not anymore.

**Comment by vkryl** [comment]
Kindly refer to [issue template](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) when submitting issues to this repository.

**Comment by AlexandrKozlovskiy** [comment]
@vkryl Why do you close this issue? Whether it not interesting for you,or you closed it,because i created issue,not using rules of issue template? If first variant,it's very pity.

**Comment by iMonZ** [comment]
> Hello. I blind user and android developer. Telegram x almost unaccessible for blind users. Do you plan improve accessibility of telegram x,or it not interesting for you? Official telegram for android accessible for us,blind users,though it have accessibility problems too,but telegram x almost fully unaccessible for blind. I can only authorize in it,and not anymore.

I would recommend blind people to use iOS.
