### ISSUE TITLE
Sending Self-Destructing Media results in blury reveal

### ISSUE THREAD

**Issue by lycano** [TGX-Android/Telegram-X#168]
**Issue Description**
* When sending a self destructing picture via cloud chat official telegram users wont get a clear picture on reveal.
* When sending a self destructing video via cloud chat official telegram users wont be able to see the playing video on reveal.

**Result**
* The image is blured when sending self desctructing image
* The first frame of a video that was send via self destruct is show blurred but the video is not playing. Its just a static blurred image.

**Expected Result**
* The revealed image is not blury and visible as originaly send
* The revealed video should play as originally send

**How to reproduce**
1. Send self destructing image or video from gallery
2. Receive self desctructing image/vide via another phone who has official telegram installed
3. Open via hold and press
4. See blurry image for an image
5. See blurry first frame for a send video

**Requirements on sender side**
* Android phone with latest Firmware
* Telegram X version 0.24.9.1530-arm64-v8a

**Comment by Sajilck** [comment]
This is not a Telegram X issue. This is an issue with legacy Telegram Android client which is already fixed in beta
https://bugs.telegram.org/c/18201
