### ISSUE TITLE
Telegram X often doesn't send notifications

### ISSUE THREAD

**Issue by KiritoStorm** [TGX-Android/Telegram-X#190]
This is proberly caused by the internal battery saving mode from Xiaomi Devices.
(And from some other manufactors, see [Don't Kill my App](https://dontkillmyapp.com).
Even when you set the Background Settings to "No Limits" there are still limitations active you can't control.

It allways happen on restart when I haven't startet Telegram X.

On the normal Telegram App I don't have this issue.
This is a long existing problem for me, so I hope someone can fix it. :)

**Comment by Nexllon** [comment]
s10e here, also did everything in "Don't kill my App" but I'm still having the same problems.
Default telegram works fine, X doesn't receive a single notification/message unless I open the app, if it weren't for the better lock with password I wouldn't use it right now.

**Comment by BrightYC** [comment]
Asus zenfone 8 here, did everything from disabling power managment in powermaster, enabling dynamic mode/etc, nothing works. In telegram app everything works like a charm

**Comment by dexaltat** [comment]
Same problem. Galaxy A52. I'm whitelisted app, but nothing happens.

**Comment by vkryl** [comment]
Closing the issue as it's impossible to properly investigate only by the device model and the fact that user experiences some issue.

In future, there shall be some step-by-step guide regarding troubleshooting notification issues and template for submitting issues related to them after following the guide.

For now it's recommended to refer to the [testing community](https://t.me/tgandroidtests) regarding any issues receiving notifications.
