### ISSUE TITLE
[Request] Tap and swipe

### ISSUE THREAD

**Issue by Archeix7** [TGX-Android/Telegram-X#192]
https://user-images.githubusercontent.com/51048550/178730789-6e1b1fcd-fdce-4556-8443-926ee2d9cee1.mp4

**Comment by Feday111** [comment]
Спасибо

**Comment by dotvhs** [comment]
This is already implement in much more convenient way. Select two message: the beginning where you want to select and the end, then hit the icon at the top as on the video and it will do the same thing without forcing you to wait on scroll:


https://user-images.githubusercontent.com/681416/181384851-6caac1a4-5b80-4249-823b-dc3e278d1c0c.mp4

**Comment by vkryl** [comment]
Not planned as there's a faster way of batch selecting available in Telegram X described above by @dotvhs.
