### ISSUE TITLE
Notifications only appear when i open an application

### ISSUE THREAD

**Issue by Kristin0** [TGX-Android/Telegram-X#204]
I receive my notifications from chats only when i open an app. I tried another network connection (4g, wifi-s), but issue is the same. Then to check i've downloaded official telegram, and notifs from it works fine. All configs in my phone is default (no priority for notifs). When the app is opened i receive notifs, when i close it (aka kill app), no notifs..Strange issue, it wasn't there before...

1. Use `'Copy Report Details'` from the app's Settings
Telegram X 0.24.9.1530-arm64-v8a (a0dc1b0d)
Android S(31)
samsung SM-S901U1 (SP1A.210812.016.S901U1UEU2AVG8)

7. A brief description of *Expected* and *Observed* behavior must be provided;
Expected - notifications are correctly showed on notif bar when app is closed
Observed - no notifs from chats 

9. APK source is included – Google Play Store or another app market, Telegram Channels, etc.
Google Play Store

**Comment by vkryl** [comment]
Could you please install 1544 version and share error details here to confirm it's FIS_AUTH_ERROR?

https://t.me/tgx_log/485

**Comment by Kristin0** [comment]
@vkryl yeah, it fixes issue, thanks!!! Reactions are also great
