### ISSUE TITLE
Secret chats messages not getting delivered to iOS client

### ISSUE THREAD

**Issue by ondrepe** [TGX-Android/Telegram-X#206]
Messages from secret chats are not sent. The reciever can see just empty notifications, Only one tickbox is displayed.. It started on 8/13. Not able to screenshot it, because it is a secret chat screen.

Google Play
Telegram X 0.24.9.1530-arm64-v8a (a0dc1b0d)
Android S(31)
Sony XQ-AS52 (58.2.A.10.33)

**Comment by vkryl** [comment]
What app is used on the other side?

**Comment by ondrepe** [comment]
iOS version of standard Telegram client

**Comment by vkryl** [comment]
It seems to be an issue with iOS app (receiving side), as Telegram X <-> Telegram X or any non-iOS client chain works properly. Will confirm later.

**Comment by vkryl** [comment]
It's a problem of TDLib (any client) <-> iOS only. Are you able to receive messages from iOS side?

**Comment by ondrepe** [comment]
yep, i am able to recieve messages from iOS

**Comment by snai** [comment]
I have the same issue and also opened a bug report at https://bugs.telegram.org/c/19900

**Comment by snai** [comment]
Further bug reports on the same issue:

https://bugs.telegram.org/c/15961

https://bugs.telegram.org/c/19963

**Comment by MrDemous** [comment]
This is fixed on the latest Telegram X beta but I can't seem to send videos over secret chats to iOS users

**Comment by vkryl** [comment]
Even though it is iOS client's issue, the issue seems to be resolved by updating to the latest version of Telegram X (`0.25.1.1560`) and iOS client by now. If not, this issue will be reopened.

**Comment by 0xInuarashi** [comment]
is telegram x still available for ios?
