### ISSUE TITLE
[Feature Request] Improve voice message canceling

### ISSUE THREAD

**Issue by ruineka** [TGX-Android/Telegram-X#213]
My friends and I have constantly dealt with accidently deleting messages with how telegram currently handles the send/delete of the message. Could we change the ranges of the slider to make it harder to accidentally delete the message?

I feel if we make it where you need to slide your figure over more it would resolve this issue.

**Comment by vkryl** [comment]
Will think about it, but can't guarantee whether it will be changed or not, as previously there were no similar feedback & currently busy with other tasks. Meanwhile keep in mind it's possible to lock the voice message recording by swiping the button up to avoid accidental cancellations & hands-free recordings.

**Comment by ruineka** [comment]
> Will think about it, but can't guarantee whether it will be changed or not, as previously there were no similar feedback & currently busy with other tasks. Meanwhile keep in mind it's possible to lock the voice message recording by swiping the button up to avoid accidental cancellations & hands-free recordings.

I could look into it and maybe put something together and open a PR to be merged if there is any interest.

Thanks for the quick reply.

**Comment by vkryl** [comment]
I don't see any problem if current behaviour kept unchanged for now, but there would be a small slider in `Settings — Interface` above `Voice Messages` header that would look clean & allow increasing the swipe length needed to cancel voice or video message. Such PR could be accepted.

**Comment by vkryl** [comment]
Having to close this issue since there's no movement on this issue and it doesn't meet the [issue reporting guide](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) criteria (feature request).
