### ISSUE TITLE
Default reaction in swipe action setting

### ISSUE THREAD

**Issue by SupinePandora43** [TGX-Android/Telegram-X#218]
Currently there's only `Share` and `Reply`, but no `Default Reaction` (👍) that appears on swipes in groups and own channels.

Also there's no way to set default reaction.

![IMG_20220914_160344.jpg](https://user-images.githubusercontent.com/36124472/190137529-45ffdf1e-1a6c-4478-a324-17243e26aafb.jpg)

**Comment by vkryl** [comment]
It is controlled by Settings — Themes and Chats — Quick Reaction.

**Comment by SupinePandora43** [comment]
> It is controlled by Settings — Themes and Chats — Quick Reaction.

Thanks, but there's no way to disable default reaction in swipe menu

**Comment by vkryl** [comment]
There is. Check the setting.

**Comment by SupinePandora43** [comment]
> There is. Check the setting.

![IMG_20220916_094415.jpg](https://user-images.githubusercontent.com/36124472/190558414-3c20204a-a12e-495d-b9dc-69f39a4deb20.jpg)

Only this
![IMG_20220916_094457.jpg](https://user-images.githubusercontent.com/36124472/190558492-39eacb44-dc28-44d6-bdfb-12dd535f6ab2.jpg)

And it doesn't say how to trigger it

**Comment by Sajilck** [comment]
You just need to disable the quick reaction

**Comment by SupinePandora43** [comment]
> You just need to disable the quick reaction

Even when disabling quick reaction it doesn't show up in swipe menu settings

**Comment by Sajilck** [comment]
@SupinePandora43 when quick reaction is disabled, there is no swipe action for reaction. Then why it has to show in Swipe actions settings?

**Comment by SupinePandora43** [comment]
> @SupinePandora43 when quick reaction is disabled, there is no swipe action for reaction. Then why it has to show in Swipe actions settings?

It's enabled
