### ISSUE TITLE
Implement channel post commentary view

### ISSUE THREAD

**Issue by SupinePandora43** [TGX-Android/Telegram-X#220]
Right now TGX just shows linked chat group with focus on post.

It doesn't provide way to comment on a post without entering group chat.

**Comment by vkryl** [comment]
Closing this issue as it's a feature request without suggested mockups to be evaluated (to have it formatted as `task`-type issue).

**Comment by SupinePandora43** [comment]
> Closing this issue as it's a feature request without suggested mockups to be evaluated (to have it formatted as `task`-type issue).

I made it use your `task`-type issue template
