### ISSUE TITLE
no push notifications

### ISSUE THREAD

**Issue by f242** [TGX-Android/Telegram-X#222]
redmi 9 pro plus
android 12
tgx 0.25.0.1555-arm64-v8a from google play

With the same settings, the regular telegram app works without any problems with notifications
Settings: disabled background traffic transfer, disabled work in the background mode

**Comment by vkryl** [comment]
Regular Telegram app, unlike Telegram X, is usually whitelisted by the system on redmi devices (in the past system allowed it ignoring some of the settings). If you don't see any error in Settings — Notifications, try to look for help in https://t.me/tgandroidtests, maybe someone might help you adjust the settings to make notifications work.
