### ISSUE TITLE
Premium reactions not available to normal users like in other telegram clients

### ISSUE THREAD

**Issue by Giulianini** [TGX-Android/Telegram-X#226]
![photo_2022-09-21_09-35-27](https://user-images.githubusercontent.com/39558398/191443806-58ed17b7-e406-475c-b623-84b59ad64a78.jpg)

**Comment by Loiszn** [comment]
🚀🚀🚀🚀🚀

**Comment by vkryl** [comment]
Unfortunately, the server intentionally marks these reactions as premium-required for apps that are based on pre-custom-reactions API layer. Will get automatically resolved with TDLib upgrade.
