### ISSUE TITLE
Can not log into existing account

### ISSUE THREAD

**Issue by majstar** [TGX-Android/Telegram-X#228]
Hello.
Official Telegram clients have an option to "Send code as SMS" even if you already have another active login session. Telegram X does not seem to offer this option. I tried to log into my existing account via Telegram X, but the app offers only sending the log-in code to another device. The worst part is I do not have other devices with active Telegram sessions for that account.

It would be better if Telegram X allowed to choose which way I would prefer to get verification code. Please add "Send the code via SMS" button or something like that.

**Comment by vkryl** [comment]
You should be able to press "Didn't receive the code?" button in the bottom-left corner.
