### ISSUE TITLE
Feature request  Lower background media player volume when play the voice message

### ISSUE THREAD

**Issue by stanleypang86** [TGX-Android/Telegram-X#229]
The guide below provides the flow for creating a perfect issue report to the Telegram X Repository. Before submitting, ensure that it complies with the following principles. 

## Your report must be:
- [ ] **Appropriate**. Only *bugs* can be included.
- [ ] **Structured**. Stick to the following path:
1. Use `'Copy Report Details'` from the app's Settings;
2. Include the public message link for reports involving media;
3. Attach a screenshot or video that clearly represents the issue in your report. Kindly change the app's language to English before recording those; 
4. A brief description of *Expected* and *Observed* behavior must be provided;
5. APK source is included – Google Play Store or another app market, Telegram Channels, etc.
- [ ] **English** is the only language accepted.  

## Your issue must not be a:
- [x] **Feature Request**. Designers are welcome to propose properly crafted feature requests via [Telegram Designers](https://t.me/designers) or share ideas in [Telegram X Developers](https://t.me/tgx_dev), given they include *finalized* mockups and match the overall app quality.
- [ ] **UX Preference**. We won't consider those as issues. If you are a developer and believe some change would improve user experience on all devices, consider submitting a [pull request](https://github.com/TGX-Android/Telegram-X/blob/main/docs/PULL_REQUEST_TEMPLATE.md).

*All these mentioned above will be declined.*
 
## A note on device-specific issues:
Specific issues you can reproduce on your end can be caused by the device itself and be device-dependent. Such issues do not mean to occur for everyone. Please be patient with those – fixing such issues can be time-consuming. 

Good luck, and thanks for the contribution!

**Comment by mactrash** [comment]
I second about this... Now the notify sound will lower the background media player volume but when play back the voice message will not lead to difficult to hear the voice message except first paused the player

**Comment by vkryl** [comment]
See [issue reporting guide](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) (feature requests part).

**Comment by stanleypang86** [comment]
I just want to solve the problem. I believe that many people have encountered this problem, but it seems that it has little effect on others. Why do you need to fill in the form? @vkryl

**Comment by soheilysf** [comment]
I'm seconding this request. Telegram used to automatically and temporarily lower playback volume as soon as you started recording a voice message and after you finished recording the message the playback volume reverted back.
This got removed at some point recently and many times while I'm playing music on my phone, or on my Bluetooth speaker or in the car, I have to first manually lower the volume and then start recording a voice message otherwise the background music will destroy the quality of my voice message. 
Please please add this feature. It's the most annoying thing and it happens frequently.
