### ISSUE TITLE
Big animated custom emoji aren't looped in chat

### ISSUE THREAD

**Issue by Whitebrim** [TGX-Android/Telegram-X#230]
I'm using latest beta version from Google Play.

**Current behaviour:** If old settings like "Animated Emoji" and "Loop Animated Stickers" are on, in chat view new premium animated emoji stop playing and need to be tapped to loop one more time. It occurs only messages that contain one emoji with no text, so emoji became big emoji.

**Expected behaviour:** in chat view big animated (custom) emoji are automatically looped.

**Comment by vkryl** [comment]
Currently it's intended behaviour until viewing & installing emoji sets would be supported by the app.
