### ISSUE TITLE
Quick reaction scroll is counterintuitive 

### ISSUE THREAD

**Issue by Whitebrim** [TGX-Android/Telegram-X#232]
We're all used to the "drum shaft" scroll view, where swiping up raises the scroll view up, like the time picker on the iPhone.
But it scrolls opposite side for the current quick reactions implementation.
Please add an option to invert scroll, or just invert your inverted scroll :/

**Comment by vkryl** [comment]
See [issue reporting guide](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) (UX Preference part).
