### ISSUE TITLE
Feature request: option to disable reactions 

### ISSUE THREAD

**Issue by DavertMik** [TGX-Android/Telegram-X#234]
Since last update Telegram X introduced reactions to messages similar to official client.

It would be nice if reactions all together could be disabled in UI settings. I used telegram X for years and never needed them and now I find them annoying.

**Comment by vkryl** [comment]
See [issue reporting guide](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) (feature request part).
