### ISSUE TITLE
🏆 Telegram X Android Competition: Round 2. Comments + Message Threads

### ISSUE THREAD

**Issue by vkryl** [TGX-Android/Telegram-X#235]
**Task description and mockups**: https://contest.com/docs/TgX-Oct22-Round2#1-channel-comments-message-threads
**Deadline**: 23:59 on October 30th (Dubai time).
**Bounty**: $9,000
**Terms**: https://t.me/contest/300

Reference this issue when submitting a pull request that implements this task.

**Comment by xerta555** [comment]
Hi

I see that theses new functions have been merged and are now closed, but on my Telegram X (version 0.25.2.1574 arm64) i don't get all the groups for which i already see them with Telegram app.
I speack about this new feature in the original Telegram app: https://telegram.org/blog/topics-in-groups-collectible-usernames/fr?setln=en

Is it normal ?
When it will be visible in Telegram X app ?

Thx
