### ISSUE TITLE
APK support

### ISSUE THREAD

**Issue by xIUPITERx** [TGX-Android/Telegram-X#260]
With Telegram X I am unable to install apks or save them to the download folder. In the normal Telegram app it works just fine.

**Comment by xIUPITERx** [comment]
Any news?

**Comment by vkryl** [comment]
Not enough details.

**Comment by xIUPITERx** [comment]
What details do you need?

**Comment by xIUPITERx** [comment]
Due to the security policy I can't even take a screenshot / recording of the app.

**Comment by xIUPITERx** [comment]
@vkryl 
Have you tried it yourself to install apks with telegraph x ?

**Comment by RememberTheAir** [comment]
Installing APKs work from my Telegram X. If you're going to report a bug, at least include your app's version, the phone you're using, the android version, and the detailed steps to reproduce the issue or a decent description of what's not working (what does "unable to install apks" mean? The app is unresponsive when you tap on an apk file? An error pop-up is displayed? There's no "save to download"options in an apk's context menu? How is the developer supposed to figure out where's the issue if he doesn't know what he's supposed to fix?)

You can report these issue in https://t.me/tgandroidtests, with a detailed description of the issue

**Comment by xIUPITERx** [comment]
I am using a Samsung A52s 5G, with One UI 4.1 based on Android 12.
When I try to open a downloaded APK file, I get the following error message:
"Application to open this file not found".
The problem does not occur when I give the app access to my photo (media) folders.
