### ISSUE TITLE
no notifications from second account

### ISSUE THREAD

**Issue by Nammehub** [TGX-Android/Telegram-X#273]
Telegram X can be active in several accounts at the same time.
I use two accounts. Not receiving notifications for messages from the second account.
The problem is not obvious: at the first time, notifications come from the second account. But after some time, notifications disappear and no longer come from the second account.

Telegram X 0.25.1.1560-arm64-v8a (269a0759)
TDLib: 1.8.5 (tdlib/td@86294f2)
Android: 11 (30)
Device: Xiaomi Redmi M2004J19C (RP1A.200720.011)
Screen: 2134x1080 (density: 2.8812501, fps: 60.0)
Build: `Redmi/galahad_ru/galahad:11/RP1A.200720.011/V12.5.5.0.RJCRUXM:user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by notfullmetal** [comment]
I second this issue. I have 3 accounts added and it will only send me notification from the 2nd account. If I logout from 2nd then it will only send noti from 3rd and if I logout from that as well, then finally it will send notification from the 1st/only account added.

Rather annoying, hoping this will fix shortly.

**Comment by vkryl** [comment]
> _But **after some time**, notifications disappear and no longer come from the second account._

The issue doesn't seem to be easily reproducible. Needs extensive testing with TDLib logs to determine after what event notifications from certain accounts stop arriving.

**Comment by gcvl** [comment]
I have this happening with 0.25.8.1629.
I'm on A13 (LineageOS) and I noticed that the system notifications channel for the second account gets regularly deleted and it stops getting notifications no matter how I set it from TGX.

**Comment by gcvl** [comment]
> > _But **after some time**, notifications disappear and no longer come from the second account._
> 
> The issue doesn't seem to be easily reproducible. Needs extensive testing with TDLib logs to determine after what event notifications from certain accounts stop arriving.

@vkryl   Steps to reproduce:

1) Log into the 1st account;
2) Log into the 2nd account;
3) Enable notifications for all of them;

4) From a 3rd account, send a message to the 1st one, then to the 2nd one and _then again to the 1st one_.
One of them will lose all the Android notification channels and just stop notifying the user.

Currently the only way to get around this is to clone TGX to a work profile or use a third-party client.


Telegram X 0.26.3.1668-arm64-v8a (d69b6e66)
PRs: #504 (ceb2d256)
TDLib: 1.8.22 (tdlib/td@85c8c19)
Android: 13 (33)
Device: OnePlus OnePlus IN2013 (lineage_instantnoodle-userdebug 13 TQ3A.230901.001 f2915e0724)
Screen: 2142x1080 (density: 2.8125, fps: 60.000004)
Build: OnePlus/OnePlus8/OnePlus8:13/RKQ1.211119.001/Q.129a9e4-1-2:user/release-keys
Package: org.thunderdog.challegram
Locale: it_IT (app: it)
Installer: com.android.packageinstaller
APK Fingerprint: 66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68

**Comment by engproali** [comment]
i have the same issue with iPhone 15 pro on ios 17.2 and the last telegram update
