### ISSUE TITLE
video playback - unauthorized overlay

### ISSUE THREAD

**Issue by mxdpeep** [TGX-Android/Telegram-X#274]
Clicking on a YouTube video link opens a video, starts playing and then stops in a second with a message **UNAUTHORIZED OVERLAY**.

Telegram X 0.25.2.1572-arm64-v8a (a49de56e)
PRs: #256 (6b516dca)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: 12 (31)
Device: motorola motorola moto g(60) (S2RIS32.32-20-7-4)
Screen: 2225x1080 (density: 2.5, fps: 120.00001)
Build: `motorola/hanoip_retailenq/hanoip:12/S2RIS32.32-20-7-4/41d937-0279a:user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by vkryl** [comment]
Does this always happen or requires some additional steps (i.e. trying to play video in full-screen, etc)? Can't reproduce on Samsung device.

**Comment by Sajilck** [comment]
This will happen when an another app does something else on top of the player.
Example, while playing the video, swipe down the notification panel. The YouTube player will be paused with error UNAUTHORISED OVERLAY

**Comment by vkryl** [comment]
Not enough information to resolve the issue for the specific situation.
