### ISSUE TITLE
Link in supergroups to view older history doesn't work anymore

### ISSUE THREAD

**Issue by 0x3e24** [TGX-Android/Telegram-X#275]
Groups that are upgraded to supergroups display a link to the archived group as the first message 
(`Group upgraded to supergroup. Tap here to view older history.`)

**Expected**: Tapping the text opens up the archived (standard) group. 
**Observed**: Context menu opens up from the bottom (`Reply, Copy link, More`). The group and messages that are displayed remain the same. 

---

Telegram X 0.25.2.1573-arm64-v8a (0d80ea9b)
PRs: #256 (a4654258)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: 11 (30)
Device: Xiaomi Xiaomi Mi 9T (RKQ1.200826.002 test-keys)
Screen: 2210x1080 (density: 2.75, fps: 60.000004)
Build: `Xiaomi/davinci_eea/davinci:11/RKQ1.200826.002/V12.1.1.0.RFJEUXM:user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by vkryl** [comment]
Shall be fixed once `tdlib-topics` branch will be merged.
