### ISSUE TITLE
Input hint text is not vertically centered

### ISSUE THREAD

**Issue by alth25th** [TGX-Android/Telegram-X#279]
If you set a small font size in the system settings, the input hint text is not centered vertically relative to the icons, but is placed a little higher. The screenshots below show how the input hint text is placed with different font sizes.

**Expected behavior:** the input hint text with a small font size is centered vertically relative to the icons, as with other font sizes.
**Observed behavior:** the input hint text is placed a little higher.

APK source: Telegram Channel [Telegram X APKs & Build Info](https://t.me/tgx_log)

**Small Font Size**
![Screenshot_20221130-135143_Telegram X](https://user-images.githubusercontent.com/75804339/204791121-64239933-1d13-4340-abaf-05824740d3b9.png)

**Default Font Size**
![Screenshot_20221130-135203_Telegram X](https://user-images.githubusercontent.com/75804339/204791129-6bb59d9f-2f59-44d2-a99e-1ee67030bc9d.png)

**Large Font Size**
![Screenshot_20221130-135216_Telegram X](https://user-images.githubusercontent.com/75804339/204791112-c8204e94-a0a5-41cd-b424-17bcdb3f6b49.png)

**Largest Font Size**
![Screenshot_20221130-135234_Telegram X](https://user-images.githubusercontent.com/75804339/204791136-d544c291-2ae1-466d-9777-0765f2e90f3e.png)

**Report Details**
Telegram X 0.25.2.1574-arm64-v8a (f4511a77)
PRs: #246 (c7f58f68)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: 12L (32)
Device: Xiaomi Xiaomi Mi A1 (lineage_tissot-userdebug 12 SQ3A.220705.004 13153b99e1)
Screen: 1920x1080 (density: 2.75, fps: 60.000004)
Build: `xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/8.1.10:user/release-keys`
Package: org.thunderdog.challegram
Installer: com.android.packageinstaller
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by vkryl** [comment]
Already fixed @Arseny271, coming soon in beta.
