### ISSUE TITLE
Themed icon

### ISSUE THREAD

**Issue by dexaltat** [TGX-Android/Telegram-X#281]
According to this PR:

 https://github.com/TGX-Android/Telegram-X/commit/1596ce50800623dad593352dfd67158b898a1d2c

themed icon is off on Samsung devices. But in Android 13 Samsung devices get support this for third party apps. This can be seen in the screenshot. Time to activate it again.

![Screenshot_20221204_222504_One UI Home.jpg](https://user-images.githubusercontent.com/76195431/205514189-2bcf6e96-f4ed-4c4c-a18c-64792c6a3a42.jpg)

**Comment by dexaltat** [comment]
Fixed, thanks.

**Comment by vkryl** [comment]
Just FYI even though it's in beta, it is not yet merged and might be reconsidered for the stable release.

**Comment by dexaltat** [comment]
![Screenshot_20221223_180330_One UI Home.jpg](https://user-images.githubusercontent.com/76195431/209365063-bd172b25-8b4f-4fee-b34b-7476958230d2.jpg)
 In 1580 the icon are no longer themed

**Comment by dexaltat** [comment]
> Just FYI even though it's in beta, it is not yet merged and might be reconsidered for the stable release.

![Screenshot_20221223_180330_One UI Home.jpg](https://user-images.githubusercontent.com/76195431/209365331-205065c4-57cd-462c-8459-e1f891667b41.jpg)

in 1580 the icon is again not themed

**Comment by vkryl** [comment]
@dexaltat it's going to be back in the next beta, it happened just because current beta is based on `tdlib-topics` branch, which is 2 commits behind `main` (one of which includes themed icon).
