### ISSUE TITLE
Звонок через Bluetooth ломает звук системы на Pixel устройствах 

### ISSUE THREAD

**Issue by Fenrir784** [TGX-Android/Telegram-X#282]
После звонка через Bluetooth перестает работать любой звук в наушниках, даже от сторонних приложений, микрофон работает. 

Если не брать трубку - поведение не повторяется.
Лечится только переподключением наушников.
Повторяется почти каждый раз на разных телефонах и моделях наушников, багу минимум 2 года. 

Данное поведение было подтверждено несколькими участниками русскоязычного чата Telegram X.

```
Telegram X 0.25.2.1574-arm64-v8a (f4511a77)
PRs: #246 (c7f58f68)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: 13 (33)
Device: Google google Pixel 4a (T1B3.221003.008)
Screen: 2140x1080 (density: 2.6625001, fps: 60.000004)
Build: `google/sunfish/sunfish:13/T1B3.221003.008/9245559:user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`
```

**Comment by vkryl** [comment]
Чтобы воспроизвести проблему, гарнитура должна быть подключена перед звонком? Или во время звонка надо подключить? Можно описать в виде шагов с двух устройств, на SGS10 не захотело воспроизводиться по описанию.

**Comment by Fenrir784** [comment]
@vkryl Похоже звонок TGX как-то оставляет за собой звуковой фокус или режим гарнитуры у наушников.

Порядок действий:
Свежеребутнутый телефон
Подключаю наушники (Сейчас проверяю на Soundcore Liberty 2 Pro)
Захожу в телеграмм и звоню, дожидаюсь подключения, слышу собеседника, сбрасываю
После окончания звонка если позвонить ещё раз, то звук останется
Если после окончания звонка включить что-то (Проверено на AIMP, Youtube, Встроенном плеере TGX), то оно звучать не будет до переподключения гарнитуры ИЛИ до ручного завершения процесса TGX.
Если зайти в другое приложение для звонков (Проверено на Discord) и кому-то позвонить во время отсутствия звука - звук в звонке работать будет.

Всё время когда звук отсутствует гарнитура тихо шипит даже без проигрываемого звука, линк не уходит в сон.

Проверял только на Пикселях, других телефонов под рукой нет (1, 4a и другой 4a. Андроид 10/13/13 соответственно) - везде воспроизводится.
Не уверен с какой версии началось именно такое поведение. Раньше звук умирал полностью и при повторном звонке звука не было. Теперь звонки остаются работать, но если сразу после звонка включить музыку, то ничего не будет.

**Comment by vkryl** [comment]
@Fenrir784 Завершать звонок нужно с какой-то конкретной стороны или не влияет? На устройствах Samsung совсем не воспроизводится, Android 13 (OneUI 5.0). [TGCallService.releaseAudioFocus](https://github.com/TGX-Android/Telegram-X/blob/66a72cdccbc00a3cd4675d2e923c3d73481c743c/app/src/main/java/org/thunderdog/challegram/service/TGCallService.java#L331) вызывается и выполняется корректно, в нём фокус сбрасывается. Нет под рукой пикселя, чтобы проверить на нём.

**Comment by vkryl** [comment]
@Fenrir784 можно ещё записать Application Log с тегом `VOIP` включенным записать в `VERBOSE`?

**Comment by vkryl** [comment]
> @vkryl Поведение не отличается при сброса вызова мной и получателем.
> 
> [1574.0 (call ended by recipient).log](https://github.com/TGX-Android/Telegram-X/files/10154788/1574.0.call.ended.by.recipient.log)
> 
> [1574.0 (call ended by me).log](https://github.com/TGX-Android/Telegram-X/files/10154785/1574.0.call.ended.by.me.log)

В этих логах тег `VOIP` не включен.

**Comment by Fenrir784** [comment]
@vkryl 
Почему-то не включился, хотя я выбрал.
Вот с ним, проверил что он там есть.
[1574.0 (1).log](https://github.com/TGX-Android/Telegram-X/files/10154826/1574.0.1.log)

**Comment by vkryl** [comment]
@Fenrir784 можно на этой сборке проверить, что исправилось: https://drive.proton.me/urls/DSYEZPVHYR#vzFOdNwQj1Bk

**Comment by vkryl** [comment]
Тогда по бете будет видно. Если не исправилось, переоткрою.

**Comment by Fenrir784** [comment]
@vkryl Больше не воспроизводится, спасибо за фикс. 
Фокус возвращается как надо.
