### ISSUE TITLE
Audio file restarts from beginning when audio bar closed

### ISSUE THREAD

**Issue by nicolapace** [TGX-Android/Telegram-X#284]
When closing an audio bar and then re-playing the same audio file that was in play before, this audio restarts from the beginning but not from where I left, as for example in Telegram.

Telegram X 0.25.2.1575-arm64-v8a (66a72cdc)
PRs: #246 (e5066e99)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: 12 (31)
Device: Xiaomi POCO M2007J20CG (SKQ1.211019.001 test-keys)
Screen: 2265x1080 (density: 2.75, fps: 120.00001)
Build: `POCO/surya_eea/surya:12/SKQ1.211019.001/V13.0.3.0.SJGEUXM:user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by Ramazan1512** [comment]
Telegram X 0.25.2.1575-arm64-v8a (66a72cdc)
PR'ler: #246 (e5066e99)
TDLib: 1.8.7 ( https://github.com/tdlib/td/commit/76f5f33 )
Android: 12 (31)
Cihaz: Xiaomi POCO M2007J20CG (SKQ1.211019.001 test anahtarları)
Ekran: 2265x1080 (yoğunluk: 2,75, fps: 120,00001)
Yapı: POCO/surya_eea/surya:12/SKQ1.211019.001/V13.0.3.0.SJGEUXM:user/release-keys
Paket: org.thunderdog.challegram
Yükleyici: Google Play
Parmak İzi:66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68

**Comment by vkryl** [comment]
It's not a bug, it's missing feature.
