### ISSUE TITLE
Arrow down icon not disappearing

### ISSUE THREAD

**Issue by AndRo-Marian** [TGX-Android/Telegram-X#285]
The arrow icon not disappearing when scrolling down and I am at the end already.

I think is happening when I have new messages and I don't read to end and I reply to one.

Telegram X 0.25.3.1576-arm64-v8a (49538abb)
PRs: #283 (77196048)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: Oreo (26)
Device: HUAWEI HUAWEI WAS-LX1 (WAS-LX1 8.0.0.394(C432))
Screen: 1794x1080 (density: 3.0, fps: 60.000004)
Build: `HUAWEI/WAS-LX1/HWWAS-H:8.0.0/HUAWEIWAS-LX1/394(C432):user/release-keys`
Package: org.thunderdog.challegram
Installer: Google Play

**Comment by vkryl** [comment]
Unclear what arrow icon is meant, please provide some screenshots.

**Comment by AndRo-Marian** [comment]
The scroll arrow.
After pressing on a replied message and jumps up, qfter scrolling down to bottom the arrow is not hidden as normal.

**Comment by vkryl** [comment]
This happens because after you press on a replied message the button will take to the reply message & highlight it, which isn't always at the bottom (also if you scroll further down from the reply message, the arrow will change its direction to upward position)

**Comment by AndRo-Marian** [comment]
I don't want that behavior to jump back up
