### ISSUE TITLE
Missing recorded videos in builtin select gallery

### ISSUE THREAD

**Issue by Numenorean** [TGX-Android/Telegram-X#293]
Videos captured in the system camera, originally saved to /InternalSorage/DCIM/Camera, are NOT displayed in Telegram X pop-up built-in gallery, though the images are located in the same directory and ARE displayed

**Builtin gallery**
![Builtin gallery](https://user-images.githubusercontent.com/41187266/210082740-33e43c7b-a567-4c49-a4d7-910a42ed528a.png)

**System gallery**
![System gallery](https://user-images.githubusercontent.com/41187266/210082798-20874098-fdbb-4f59-bb03-36b845986869.png)

**Recently recorded video which are not displayed in TGX**
![Recently recorded video which are not displayed in TGX](https://user-images.githubusercontent.com/41187266/210082853-2060d20a-ce01-4944-956d-f078a2332826.png)

**Photo in the same directory which ARE displayed**
![Photo in the same directory which ARE displayed](https://user-images.githubusercontent.com/41187266/210082970-581312ed-c7a8-432b-b286-b13d9ec108d9.png)

## Steps to reproduce

Can't say for sure, it seems on other devices or video's locations, the videos are shown

This problem has been previously posted here https://t.me/tgandroidtests/52545 in the 2018

```
Telegram X 0.25.3.1581-arm64-v8a (d0306cda)
TDLib: 1.8.9 (tdlib/td@8ee04b3)
Android: 10 (29)
Device: HUAWEI HONOR HLK-AL00 (HLK-AL00 2.0.0.213(C00E210R8P2))
Screen: 2340x1080 (density: 3.0, fps: 60.000004)
Build: HONOR/HLK-AL00/HWHLK-H:10/HONORHLK-AL00/102.0.0.213C00:user/release-keys
Package: org.thunderdog.challegram
Installer: org.thunderdog.challegram
Fingerprint: 66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68
```

**Comment by vkryl** [comment]
Must be an issue of the app used to record these videos. Each media has to be scanned with the system MediaScanner service before it appears in gallery. System gallery you have most likely shows files by scanning device storage directly, which isn't an option for the app. You should see videos by using some tool for triggering MediaScanner, if it doesn't help, then there's a problem with the MediaScanner in the Android build you are using.

**Comment by Numenorean** [comment]
@vkryl I found out that if you step into the "Send media without compression" and then tap on three dots then you can actually find recently recorded video. However if you tap on three dots just from builtin gallery and select "Gallery" (which is supposed to have the same behavior as phone gallery) then there is still do displayed only media which was in the pop-up gallery. Here it's an example [video](https://user-images.githubusercontent.com/41187266/213393910-711d3d0d-186e-4557-8bf6-0ea5dd89b818.mp4)

**Comment by vkryl** [comment]
@Numenorean that's because when you tap on three dots, default system gallery picker is used, not the in-app one, which may also be the regular file picker.

**Comment by Numenorean** [comment]
@vkryl I mean if I tap on three dots in the tab "Send media without compression" everything is alright, the video is shown, although if it's three dots from the gallery picker, default phone gallery opens though without needed video. I show everything in the video

**Comment by Numenorean** [comment]
@vkryl I'm kindly suggesting you to re-open the issue, because I have recently discovered that such kind of videos ARE displayed in main telegram client, the web version, other clients based on the original one. I'm enclosing the proof

**Official client**
![image](https://user-images.githubusercontent.com/41187266/223840926-b9157d70-a71c-418e-bdf8-cf918daa612c.png)

**TGX**
![image](https://user-images.githubusercontent.com/41187266/223840856-ad4feb8e-cf08-4802-bcbb-df90663fb9ca.png)

**Comment by vkryl** [comment]
As you told, issue isn't present when you use other camera apps. "Photos" / "Videos" prompt might be added in the flow on the video you provided in [this comment](https://github.com/TGX-Android/Telegram-X/issues/293#issuecomment-1396621095) (when tapping Attach — Gallery — Three dots), but it isn't the subject of this issue.
