### ISSUE TITLE
Chat Folder

### ISSUE THREAD

**Issue by mehranmd** [TGX-Android/Telegram-X#295]
I'd like to remind that there is no chat folder present in telegram x, since it's available for a long time in telegram clients and it's very useful for managing chats i think putting it in the order would be nice.

My sincere thanks in advance.

**Comment by vkryl** [comment]
There's folder implementation by @nikita-toropov which you can test in https://t.me/tgx_prs. This PR most likely will be merged into the client, however, closing this issue because it's not intended to use it for feature requests.
