### ISSUE TITLE
Libchallegram.23.so is missing, while build using macOS

### ISSUE THREAD

**Issue by jboxx** [TGX-Android/Telegram-X#296]
The guide below provides the flow for creating a perfect issue report to the Telegram X Repository. Before submitting, ensure that it complies with the following principles. 

## Your report must be:
- [x] **Appropriate**. Only *bugs* can be included.
- [x] **Structured**. Stick to the following path:
1. Use `'Copy Report Details'` from the app's Settings;
2. Include the public message link for reports involving media;
3. Attach a screenshot or video that clearly represents the issue in your report. Kindly change the app's language to English before recording those; 
4. A brief description of *Expected* and *Observed* behavior must be provided;
5. APK source is included – Google Play Store or another app market, Telegram Channels, etc.
- [x] **English** is the only language accepted.  

## Your issue must not be a:
- [x] **Feature Request**. Designers are welcome to propose properly crafted feature requests via [Telegram Designers](https://t.me/designers) or share ideas in [Telegram X Developers](https://t.me/tgx_dev), given they include *finalized* mockups and match the overall app quality.
- [x] **UX Preference**. We won't consider those as issues. If you are a developer and believe some change would improve user experience on all devices, consider submitting a [pull request](https://github.com/TGX-Android/Telegram-X/blob/main/docs/PULL_REQUEST_TEMPLATE.md).

*All these mentioned above will be declined.*
 
## A note on device-specific issues:
Specific issues you can reproduce on your end can be caused by the device itself and be device-dependent. Such issues do not mean to occur for everyone. Please be patient with those – fixing such issues can be time-consuming. 

Good luck, and thanks for the contribution! 

I want to try TDLib implementation using this source, however I was follow the step by steps. And while assemble the log showing that there's missing generated file which libchallengram.
There's no error shown after running setup script

![image](https://user-images.githubusercontent.com/3339451/210216047-292dde20-17b7-463e-ad6f-5561c7efff8d.png)

But this error happened every time, even after I run reset script `scripts/./reset.sh` and `scripts/./setup.sh --skip-sdk-setup` setup again

```
* What went wrong:
Execution failed for task ':app:buildCMakeDebug[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/.../AndroidStudioProjects/tgx/app/.cxx/Debug/56n1q6e3/armeabi-v7a'
  
  C++ build system [build] failed while executing:
      /Users/ajaib/Library/Android/sdk/cmake/3.18.1/bin/ninja \
        -C \
        /Users/.../AndroidStudioProjects/tgx/app/.cxx/Debug/56n1q6e3/armeabi-v7a \
        challegram.23
    from /Users/.../AndroidStudioProjects/tgx/app
  ninja: error: '/Users/.../AndroidStudioProjects/tgx/tdlib/src/main/libs/armeabi-v7a/libtdjni.so', needed by '/Users/.../AndroidStudioProjects/tgx/app/build/intermediates/cxx/Debug/56n1q6e3/obj/armeabi-v7a/libchallegram.23.so', missing and no known rule to make it
```

any spesific gradle or plugin version that I need to follow?

**Comment by vkryl** [comment]
Repository was improperly cloned (most likely git LFS was not initialized)
