### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by electr1fy0** [TGX-Android/Telegram-X#310]
1. Update to MD3 (Material Design 3).
2. Support MD3 Dynamic Colors.
3. Transparent Status Bar (one that matches with the rest of the UI).
4. Transparent Navigation Bar and content being drawn below it (like most modern apps including Google Messages do).
5. Removal of separators from various places like chat list,chat window and text area separator, etc. as they only add clutter.
6. Removal of "Connecting..." which overlays on the status bar and is mostly hidden under the device cutout.
7. Option to only display the person's name in the chat list and have equal padding from the top and bottom of the name.

**Comment by vkryl** [comment]
Closing this issue because feature requests (including design changes without any mockups or `*.tgx-theme`) are not accepted.
