### ISSUE TITLE
Incorrect behavior when trying to edit message from search results

### ISSUE THREAD

**Issue by pdkpv** [TGX-Android/Telegram-X#316]
If you filter your messages from the members section and try to edit any of them while on the search results screen - the group description screen will open.

<details>
  <summary>Screencast</summary>
  
  https://user-images.githubusercontent.com/43634070/216635388-c9ea9c11-253e-4650-b89e-b13a1d4ede6f.mp4
  
</details>

Even if you click on "Show in chat" before editing - the group description screen will still open.

Telegram X **0.25.4.1582**-arm64-v8a (f2810d1e)
TDLib: **1.8.9** (tdlib/td@8ee04b3)
Android: **12** (31)
Screen: **2132x1080**
Package: **org.thunderdog.challegram**

**Comment by vkryl** [comment]
Will include a workaround before the next stable update. The issue is just more difficult than it seems because of the way opening "messages from X" was changed after introducing improved in-chat messages search, and it was made the way it's easy to break some other scenarios.
