### ISSUE TITLE
Chat Bubbles Option Missing

### ISSUE THREAD

**Issue by froilaaaaan1** [TGX-Android/Telegram-X#318]
This app (Telegram X) have an option to toggle chat bubbles in the app settings, however it's not fully supported when i visit the settings (app info) of telegram x chat bubbles toggle is missing whereas the (Telegram Stable) have this option and no chat bubbles appearing in telegram x. add this feature please.

![Screenshot_2023-02-07-06-06-23-61_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/61849282/217100182-7f7cafe8-31f0-431e-a187-21304dcb0f1a.jpg)
(Telegram X App Info)

![Screenshot_2023-02-07-06-06-54-92_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/61849282/217100231-702ce619-dc5a-46ef-bf87-32859c396486.jpg)
(Telegram Stable App Info)

**Comment by tsiflimagas** [comment]
I think you've misunderstood what bubbles means in the settings. It refers to the frame of the messages in chats and groups. System notifications bubbles aren't supported by the app, as far as I can see, but it would be nice indeed if it would be added.
