### ISSUE TITLE
Stuck on "loading..." state after login

### ISSUE THREAD

**Issue by nikita-toropov** [TGX-Android/Telegram-X#320]
![loading](https://user-images.githubusercontent.com/4970595/218185447-c1990bb3-8b5a-4bc7-bf6b-dc665ebff595.png)

**Comment by vkryl** [comment]
Should be reproducible if current user doesn't have avatar. Please confirm if it got resolved with 91c76a8 commit.

**Comment by nikita-toropov** [comment]
Yes, it's resolved
