### ISSUE TITLE
Telegram payments not work

### ISSUE THREAD

**Issue by SharkLabDev** [TGX-Android/Telegram-X#321]
Unsupported message and the button for payment is not active. you can check payment in the official shopbot.t.me
![Screenshot_20230212_213050_Telegram X.jpg](https://user-images.githubusercontent.com/60569789/218317174-1fbf4397-1590-448f-bd74-029ecd4ef328.jpg)

**Comment by vkryl** [comment]
It is planned, but not accepting general feature requests as issues.
