### ISSUE TITLE
Chats mark as read when holding on a them to preview

### ISSUE THREAD

**Issue by Makh-b** [TGX-Android/Telegram-X#322]
When you holding on a chat to preview it, messages mark as "read".
sometimes it happens for all of the unread messages and sometimes for some of them; For example, if you have a chat with 43 unread messages, after holding on that chat you whould see the number for unread messages become 20.
And also sometime it happens instantly and sometimes it takes less than one minute.

https://user-images.githubusercontent.com/66366624/218407306-039fac9f-0670-4af5-9d47-6086dd4d4663.mp4

**Comment by vkryl** [comment]
Could you reproduce the issue with TDLib log turned on to DEBUG level? (You can share it privately to one of testing group admins or https://t.me/tdlib_bot)

**Comment by vkryl** [comment]
Please confirm whether the issue got resolved in 587f879 commit (will be published in https://t.me/tgx_log).

**Comment by meybj** [comment]
this issue still is present, i sent new Tdlib DEBUG at bot.

**Comment by vkryl** [comment]
Need yet another confirmation whether issue got resolved. Note: if you are admin in the channel you are previewing, there's still chance messages might get read, which cannot be fixed until TDLib version used by Telegram X will be upgraded.

**Comment by meybj** [comment]
Issue fixed in Telegram X 0.25.5.1590, thanks

**Comment by smiba** [comment]
Incredibly frustrating, can confirm peeking now marks messages as read.
