### ISSUE TITLE
RTL Problems

### ISSUE THREAD

**Issue by Makh-b** [TGX-Android/Telegram-X#328]
There are some problems with displaying RTL texts in tgx.
I noticed at least these three:

~~1. RTL combine with LTR~~ [fixed in 1698]
if in a RTL text a LTR word is placed in the beginning of line, that line  will be messed up:
![20230219_121303](https://user-images.githubusercontent.com/66366624/219937953-d71a8197-f2fd-424a-be03-7a91da09dd11.jpg)
the "USB-C" must be the first word in the right.

It is displayed correctly in the type section:
![20230219_121614](https://user-images.githubusercontent.com/66366624/219938121-bfec2d39-b0b3-4dc2-8631-d50eb2a85101.jpg)

**2. in the Chat List**
Incorrect displaying in TGX:
![20230219_121256](https://user-images.githubusercontent.com/66366624/219938529-3a8587e9-1fb8-4de7-a469-6af953d6f056.jpg)
![20230219_123028](https://user-images.githubusercontent.com/66366624/219938759-9614e32e-00b4-4b81-9c44-5f48a7d918cc.jpg)

Correct displaying in TG:
![20230219_121257](https://user-images.githubusercontent.com/66366624/219938571-48b67dd8-f291-4a22-80fb-4554eec613cc.jpg)
![20230219_123030](https://user-images.githubusercontent.com/66366624/219938768-b6f3390e-cf9e-47c9-9947-ba8d451970ad.jpg)

Notice the position of these:
![IMG_20230219_124009_928](https://user-images.githubusercontent.com/66366624/219939576-840352c9-0afe-4e31-89df-da2c274ce06e.jpg)
![IMG_20230219_124009_695](https://user-images.githubusercontent.com/66366624/219939582-cd8336c9-f79a-4629-9e02-2d86331ef2c7.jpg)

~~3. In Search~~ [fixed in 1699]
When searching a RTL word, it highlights the searched letters and messed up the rest of the word.
![20230219_121259](https://user-images.githubusercontent.com/66366624/219939698-be657807-fea9-465c-9bc1-9224e5544f65.jpg)
If this problem was in English, words be like this when you search them:
Suppose you are searching "teleg" and it shows you
"ram Android for x**teleg**" instead of
"**teleg**ram x for Android".

Correct displaying in TG:
![20230219_121301](https://user-images.githubusercontent.com/66366624/219939713-02c9892e-897d-44f3-a625-e9862338fd9a.jpg)

**Comment by Aphotic** [comment]
RTL bugs still exist:
https://t.me/tgandroidtests/271218
https://t.me/tgandroidtests/271219
https://t.me/tgandroidtests/271205
https://t.me/tgandroidtests/271206
thank you

**Comment by vkryl** [comment]
@Aphotic instead of commenting already closed issues, just create a new one. Thank you.
