### ISSUE TITLE
[Feature Request] Background settings

### ISSUE THREAD

**Issue by NektoNektovich** [TGX-Android/Telegram-X#339]
*Feature Request*.
Hello. I use telegram x on a tablet with android 4.1.2 because only it works on such an old version of android. But we really need to set up telegram in the background, as in the main version: work in the background and restart telegram in the background after closing. without this setting, message notifications do not come, only a call goes through 🙄

**Comment by vkryl** [comment]
Telegram X intentionally does not have that setting, because it should be able to deliver notifications automatically without any additional settings. Do you see any error message in Settings — Notifications?

**Comment by NektoNektovich** [comment]
> Telegram X intentionally does not have that setting, because it should be able to deliver notifications automatically without any additional settings. Do you see any error message in Settings — Notifications?

yes, I see a red bell🤔 whatsapp receives messages perfectly, ordinary telegrams are also no problem, but you intentionally do not allow you to use telegram x normally? 🙄

**Comment by vkryl** [comment]
> > Telegram X intentionally does not have that setting, because it should be able to deliver notifications automatically without any additional settings. Do you see any error message in Settings — Notifications?
> 
> yes, I see a red bell🤔 whatsapp receives messages perfectly, ordinary telegrams are also no problem, but you intentionally do not allow you to use telegram x normally? 🙄

Since you have a red bell, what text do you see in Settings — Notifications?

**Comment by dexaltat** [comment]
> 
> *Feature Request*.
> Hello. I use telegram x on a tablet with android 4.1.2 because only it works on such an old version of android. But we really need to set up telegram in the background, as in the main version: work in the background and restart telegram in the background after closing. without this setting, message notifications do not come, only a call goes through 🙄

4.1.2? Why not 2.3.6?

**Comment by NektoNektovich** [comment]
> > > Telegram X intentionally does not have that setting, because it should be able to deliver notifications automatically without any additional settings. Do you see any error message in Settings — Notifications?
> > 
> > 
> > yes, I see a red bell🤔 whatsapp receives messages perfectly, ordinary telegrams are also no problem, but you intentionally do not allow you to use telegram x normally? 🙄
> 
> Since you have a red bell, what text do you see in Settings — Notifications?

I clarify - not a red bell, but an exclamation mark in a red icon and below the text: notifications may not be shown when the application is closed.

**Comment by NektoNektovich** [comment]
> > _Feature Request_.
> > Hello. I use telegram x on a tablet with android 4.1.2 because only it works on such an old version of android. But we really need to set up telegram in the background, as in the main version: work in the background and restart telegram in the background after closing. without this setting, message notifications do not come, only a call goes through 🙄
> 
> 4.1.2? Why not 2.3.6?

your mother is 70 years old and needs an ultra modern tablet for one messenger?

**Comment by vkryl** [comment]
> > > > Telegram X intentionally does not have that setting, because it should be able to deliver notifications automatically without any additional settings. Do you see any error message in Settings — Notifications?
> > > 
> > > 
> > > yes, I see a red bell🤔 whatsapp receives messages perfectly, ordinary telegrams are also no problem, but you intentionally do not allow you to use telegram x normally? 🙄
> > 
> > Since you have a red bell, what text do you see in Settings — Notifications?
> 
> I clarify - not a red bell, but an exclamation mark in a red icon and below the text: notifications may not be shown when the application is closed.

Just tap it and follow the guide there.

**Comment by NektoNektovich** [comment]
> > > > > Telegram X намеренно не имеет этой настройки, поскольку он должен иметь возможность доставлять уведомления автоматически без каких-либо дополнительных настроек. Видите ли вы какое—либо сообщение об ошибке в Настройках - Уведомления?
> > > > 
> > > > 
> > > > да, я вижу красный колокольчик мышление whatsapp отлично принимает сообщения, обычные телеграммы тоже не проблема, но вы намеренно не разрешаете вам нормально использовать telegram x?  roll_eyes
> > > 
> > > 
> > > Поскольку у вас есть красный звонок, какой текст вы видите в настройках — Уведомления?
> > 
> > 
> > Уточняю - не красный колокольчик, а восклицательный знак в красном значке и под текстом: уведомления могут не отображаться при закрытии приложения.
> 
> Просто нажмите на нее и следуйте инструкциям там.

clicked - notification settings were opened. there are no instructions.

**Comment by vkryl** [comment]
@NektoNektovich can you show the screenshot of `Settings — Notifications` and just `Settings` screen? It seems to be a bug.

**Comment by NektoNektovich** [comment]
> @NektoNektovichможешь показать скриншот `Settings — Notifications`и просто `Settings`экран? Кажется, это ошибка.

![Screenshot_2023-03-14-15-23-25](https://user-images.githubuserco
![Screenshot_2023-03-14-15-24-57](https://user-images.githubusercontent.com/53621368/225004466-f51be37a-acd1-45de-9d92-48025ad7bda1.png)
![Screenshot_2023-03-14-15-26-55](https://user-images.githubusercontent.com/53621368/225004490-19b5fa6e-2d2e-4a73-ab17-40b47354481f.png)

ntent.com/53621368/225004452-d555e415-d2ad-4388-97a2-6e11a7eb1d16.png)
