### ISSUE TITLE
[Feature Request] Configuring cache transfer to a memory card

### ISSUE THREAD

**Issue by NektoNektovich** [TGX-Android/Telegram-X#340]
My tablet has little built-in memory, but a memory card is installed. Please make the setting for transferring the cache to the memory card 🙏

**Comment by FlyveHest** [comment]
+1 for this, would be a very nice feature to be able to save cache, images etc on SD card instead of main memory

**Comment by Sajilck** [comment]
Closing as this is not supported by TDLib, will be considered if TDLib adds support
https://github.com/tdlib/td/issues/380
