### ISSUE TITLE
Group "topics" / channels not shown in Telegram X

### ISSUE THREAD

**Issue by thisnameissoclever** [TGX-Android/Telegram-X#345]
In the Telegram app and on desktop, "topics" (aka "channels") are shown for groups that support them. However, in Telegram X, these topics are not shown. 
Below is a screenshot from the telegram app. These topics are not shown in telegram X, and I can't find any way to access them. 

![Screenshot_20230317_111526_Telegram](https://user-images.githubusercontent.com/16503700/225986011-aa8b03a1-6835-4386-8d35-af82633980a8.jpg)

This is a significant bug because it prevents you from sending a message in any group that uses topics, since sending a message in the group has no channel and thus the message fails unless you're replying to another existing message.

**Comment by risturiz** [comment]
Yes, support for topics should be great

**Comment by Sajilck** [comment]
Its known that Topics are not implemented in Telegram X, closing the issue to keep the tracker clean

**Comment by risturiz** [comment]
@Sajilck but its a wontfix ? or topics could be implemented in the future?

**Comment by thisnameissoclever** [comment]
> Its known that Topics are not implemented in Telegram X, closing the issue to keep the tracker clean

So it's a known issue, the app is broken on servers with topics, and yet you're not going to fix it? 
Is this due to some technical limitation in your short-sighted architecture, or just through sheer laziness? Or incompetence?

**Comment by Sajilck** [comment]
> @Sajilck but its a wontfix ? or topics could be implemented in the future?

 it will be implemented in future for sure

**Comment by risturiz** [comment]
Maybe is not a bad idea to leave this open like "feature request" ? ( to avoid other users open the same issue )

**Comment by Sajilck** [comment]
There is no plan to keep feature request issues open unless it comes with a proper mockup for the specific feature design

**Comment by aknight2015** [comment]
If you implemented Topics the way you implemented groups, namely full screen display, you'll easily surpass every other Telegram clone out there as you offer REAL alternate features.

**Comment by amin-Lotfi** [comment]
hi

**Comment by AJ7ekceu** [comment]
I need it 🗿

**Comment by MartinX3** [comment]
I switched to Forkgram.  
It works good.  

This project is dead.

**Comment by aknight2015** [comment]
Thanks. I'll check it out.
