### ISSUE TITLE
`Photo has Expired` on some messages

### ISSUE THREAD

**Issue by SpEcHiDe** [TGX-Android/Telegram-X#357]
# Steps to Reproduce:

[Related Issue](https://github.com/telegramdesktop/tdesktop/issues/5867#issuecomment-661178554)

You need a bot account and a test account.

Set a Profile Photo on the test account.

Add the bot to a group

Use the bot api method getUserProfilePhotos with the ID of the test account

Send the bot api method sendPhoto with one of the file_id received by the method above to the group.

Test Account should now delete their account Profile Photo

Restart TGx and check the group for the sendPhoto message output

# Attach a screenshot or video that clearly represents the issue in your report.
   - ![image](https://user-images.githubusercontent.com/6317196/226104624-f7cb0e7c-6390-47af-8f1b-8dd1fc911af4.png)

**Comment by PyaePhyo8612** [comment]
📞😠😁😂

**Comment by PyaePhyo8612** [comment]
> 📞😠😁😂

🦄

**Comment by Bandite08088** [comment]
What

Pada tanggal Sel, 23 Mei 2023 22.39, PyaePhyo8612 ***@***.***>
menulis:

**Comment by PyaePhyo8612** [comment]
🦋

**Comment by vkryl** [comment]
Server-defined behavior.

**Comment by SpEcHiDe** [comment]
![20230528_092550](https://github.com/TGX-Android/Telegram-X/assets/6317196/ead5fa1b-3f1c-4e04-9055-c091c26581cf)


## It is still happening daily in all my group chats 😐😐😐


can you atleast make it in a similar manner, so that caption of the message is visible similar to TAndroid ?

**Comment by PyaePhyo8612** [comment]
OLO
