### ISSUE TITLE
Delete all of my offline data 

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [TGX-Android/Telegram-X#361]
HI
In new version of beta after update and opening the telegram X  ===
All of my secret chat history deleted from telegram X !!!
But I can see my secret chat data size from telegram storage

All of my chat offline data deleted but I can see my dara size again but when open this media in chat need to download again !!!!

I lose all of my secret data now how can I access to my data losing by telegram X ????

**Comment by RazaDroid** [comment]
> HI In new version of beta after update and opening the telegram X === All of my secret chat history deleted from telegram X !!! But I can see my secret chat data size from telegram storage
> 
> All of my chat offline data deleted but I can see my dara size again but when open this media in chat need to download again !!!!
> 
> I lose all of my secret data now how can I access to my data losing by telegram X ????

Secret chats you can't access from another devices or another app, it will available in same app, if you clear data of that app it will not available there too

**Comment by agole55** [comment]
I cancelled my subscription to this account

tor. 30. mar. 2023, 12:19 skrev MD Raza ***@***.***>:

**Comment by vkryl** [comment]
If you are sure the other side of secret chat didn't delete chat history (keep in mind it's possible to delete chat history from both sides), this most likely means that TDLib database was corrupted on the last launch you had secret chat history available. When this happens, there's no way to recover any of its contents.
