### ISSUE TITLE
Calls does not work

### ISSUE THREAD

**Issue by VKSolovev** [TGX-Android/Telegram-X#374]
Calls don't work. Just there is no any sound nethither on my phone not on second phone from the begining. The indicator of the connection is low. The problem is on 2 devices, android 10 and android 13. Both apks insalled from google play. Official app works fine. Before the last update everything also worked fine

**Comment by oksakhartman** [comment]
seems libtgvoip droppred in android too

**Comment by oksakhartman** [comment]
https://github.com/TGX-Android/Telegram-X/issues/134
