### ISSUE TITLE
Secret Chat Issues 

### ISSUE THREAD

**Issue by zahidulsifat** [TGX-Android/Telegram-X#379]
I am able to send messages to the receiver and they are getting the texts but if they sends texts in return I get nothing. This happens after somedays of opening the secret chat. Using Telegram X latest on Android 13 and the other device is using latest official telegram client on Android 10.

**Comment by vkryl** [comment]
If this issue still happens, report to [@tdlib_bot](https://t.me/tdlib_bot). When experiencing issues with secret chats and at least one side of the secret chat isn't Telegram X, it's possible to report at [bugs.telegram.org](https://bugs.telegram.org/)
