### ISSUE TITLE
CloudOTP scam

### ISSUE THREAD

**Issue by Notmyn** [TGX-Android/Telegram-X#383]
I don't have telgram x but I recieve verification SMS messages from cloudotp for telegram x. Messages look like 'xxxxxx is your verification code for Telegram X.' Thank you, please fix

**Comment by vkryl** [comment]
Most likely someone enters your phone number in Telegram X for unknown reasons, there's nothing to do about it.

**Comment by payfazz99** [comment]
> I don't have telgram x but I recieve verification SMS messages from cloudotp for telegram x. Messages look like 'xxxxxx is your verification code for Telegram X.' Thank you, please fix

**Comment by Mattcol10** [comment]
Comment récupérer un autre code de vérification après avoir rater le premier
