### ISSUE TITLE
YouTube SDK deprecated

### ISSUE THREAD

**Issue by GrigorenkoPV** [TGX-Android/Telegram-X#395]
I'm pretty sure it is not possible to get the YouTube API key using the link provided in the scripts anymore:
https://developers.google.com/youtube/android/player/register

As I recall, I didn't have any trouble with this whatsoever back in February, when I contributed, but now it just says that the API is deprecated.

Wayback Machine confirms my suspicions:
https://web.archive.org/web/20230131064041/https://developers.google.com/youtube/android/player/register

A possible solution might be to provide a link to the archived page on the Wayback Machine and a link to Google's credential management page directly:
https://console.cloud.google.com/apis/credentials

**Comment by vkryl** [comment]
AFAIK Google plans to drop native frame support in their YouTube app entirely (but yet it still works in latest available `18.21.34` version), so it's better to force web frame version of this pop-up for the fork clients (and maybe even show it in Telegram X in cases when YouTube SDK fails).

**Comment by vkryl** [comment]
Resolved in 5c4d5f4
