### ISSUE TITLE
Audio call does not work

### ISSUE THREAD

**Issue by NektoNektovich** [TGX-Android/Telegram-X#419]
Samsung tablet with android 4.1.2 costs telegram x Version: 0.25.8.1629-armeabi-v7a
Commit: 4dfa8893, 05/28/2023 11:42 UTC
 0.25.8.1630 beta - 0.25.10.1641 beta versions the audio call does not work at all :( of telegram x and the sound is bad, the interlocutors complain, I can hear much worse than the usual telegram and whatsapp :(

**Comment by vkryl** [comment]
Version `0.25.8.1629` isn't latest beta. `0.25.10.1641` is (at the moment of writing this comment). See: https://t.me/tgx_log

**Comment by NektoNektovich** [comment]
> Version `0.25.8.1629` isn't latest beta. `0.25.10.1641` is (at the moment of writing this comment). See: https://t.me/tgx_log

Конечно же версия 0.25.10.1641 - последняя бета, но ей не могу пользоваться, ведь аудио звонок не работает! Правильно ли я понимаю, что исправлять это для андроид 4.1 не собираетесь? 🤔

**Comment by vkryl** [comment]
В Settings — зажать версию приложения — Application Logs — Testing Utilities — tgcalls versions методом исключения перечислите все версии списком, которые работают / не работают.

То есть уберите галочки со всех версий, и оставьте только одну, попробуйте позвонить. И так по очереди с каждой версией. Затем уберите вообще все галочки и попробуйте ещё раз.

Ещё copy report details нужен.

**Comment by NektoNektovich** [comment]
> В Settings — зажать версию приложения — Application Logs — Testing Utilities — tgcalls versions методом исключения перечислите все версии списком, которые работают / не работают.
> 
> То есть уберите галочки со всех версий, и оставьте только одну, попробуйте позвонить. И так по очереди с каждой версией. Затем уберите вообще все галочки и попробуйте ещё раз.
> 
> Ещё copy report details нужен.

Снял логи во время звонка, и телеграм вылетает. Лог verbose, voip.

**Comment by NektoNektovich** [comment]
понедельник, 24 июля 2023 г. пользователь Vyacheslav <
***@***.***> написал:
> В Settings — зажать версию приложения — Application Logs — Testing
Utilities — tgcalls versions методом исключения перечислите все версии
списком, которые работают / не работают.
>
> То есть уберите галочки со всех версий, и оставьте только одну,
попробуйте позвонить. И так по очереди с каждой версией. Затем уберите
вообще все галочки и попробуйте ещё раз.
>
> Ещё copy report details нужен.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/DkKMusjZJaCLcuGgVETjrMRHzEJvyeX7aItbsUWe5xzKg_SARCdmbn7LQIE8HlMWJj3Qq9eDsJQZm4Us5Rm9eOFnRcW5nlsISCwZFTSGZcwVwDdk57qdj1XPF54_IaSlCijZ71vgI-AWGfFFEjbSUPMLusp7pLDBVIiHGprRts4IgYS81dzKROy0LmRnUXZnUxft67aiEeg9w_Gi2NZqBvO4uwvWe9guLGf9CRYXG4UkWHGviw=s0-d-e1-ft#https://github.com/notifications/beacon/AMZDE6EQFYCQTFNYIT3JUQTXRYVU5A5CNFSM6AAAAAA2UUQCHSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTCGHOGW.gif>Message
ID: ***@***.***>

Telegram X 0.25.10.1641-armeabi-v7a (5c4d5f4f)
TDLib: 1.8.14 ***@***.***)
Android: Jelly Bean (16)
Device: samsung samsung SM-T211 (JZO54K.T211ZSANJ3)
Screen: 1024x600 (density: 1.0, fps: 60.0)
Build: samsung/lt023gzs/lt023g:4.1.2/JZO54K/T211ZSANJ3:user/release-keys
Package: org.thunderdog.challegram
Locale: ru_RU (app: ru)
APK Fingerprint: 66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68

**Comment by NektoNektovich** [comment]
понедельник, 24 июля 2023 г. пользователь Vyacheslav <
***@***.***> написал:
> В Settings — зажать версию приложения — Application Logs — Testing
Utilities — tgcalls versions методом исключения перечислите все версии
списком, которые работают / не работают.
>
> То есть уберите галочки со всех версий, и оставьте только одну,
попробуйте позвонить. И так по очереди с каждой версией. Затем уберите
вообще все галочки и попробуйте ещё раз.
>
> Ещё copy report details нужен.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/DkKMusjZJaCLcuGgVETjrMRHzEJvyeX7aItbsUWe5xzKg_SARCdmbn7LQIE8HlMWJj3Qq9eDsJQZm4Us5Rm9eOFnRcW5nlsISCwZFTSGZcwVwDdk57qdj1XPF54_IaSlCijZ71vgI-AWGfFFEjbSUPMLusp7pLDBVIiHGprRts4IgYS81dzKROy0LmRnUXZnUxft67aiEeg9w_Gi2NZqBvO4uwvWe9guLGf9CRYXG4UkWHGviw=s0-d-e1-ft#https://github.com/notifications/beacon/AMZDE6EQFYCQTFNYIT3JUQTXRYVU5A5CNFSM6AAAAAA2UUQCHSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTCGHOGW.gif>Message
ID: ***@***.***>

﻿====== CHECKPOINT 07/24/2023 12:44:30 ======
App: 0.25.10.1641-armeabi-v7a
SDK: 16 (Jelly Bean), NDK: 16 (armv7l)
Manufacturer: samsung
Model: SM-T211
Brand: samsung
Display: JZO54K.T211ZSANJ3
Product: lt023gzs
Fingerprint: samsung/lt023gzs/lt023g:4.1.2/JZO54K/T211ZSANJ3:user/release-keys
Screen: 1024x600 (1.000000)
[APP][INFO][07/24/2023 12:44:30]: accountId:0 refreshNeeded -> true
[APP][INFO][07/24/2023 12:44:30]: accountId:0 refreshActive -> true, size:6
[APP][INFO][07/24/2023 12:44:30]: 6 iterations in 14ms
[VOIP][VERBOSE][07/24/2023 12:45:15]: #1: call created, user_id:360890854
[VOIP][VERBOSE][07/24/2023 12:45:15]: #1: updateCall, userId:360890854 isOutgoing:true state:CallStatePending {
  isCreated = false
  isReceived = false
}

[VOIP][INFO][07/24/2023 12:45:16]: TGCallService.onStartCommand received, intent: Intent { cmp=org.thunderdog.challegram/.service.TGCallService (has extras) }
[VOIP][VERBOSE][07/24/2023 12:45:16]: TGCallService.onCreate
[VOIP][INFO][07/24/2023 12:45:16]: Configuring device for call...
[VOIP][DEBUG][07/24/2023 12:45:16]: notifyAudioSettingsChanged
[VOIP][VERBOSE][07/24/2023 12:45:16]: #1: updateCall, userId:360890854 isOutgoing:true state:CallStatePending {
  isCreated = true
  isReceived = false
}

[VOIP][VERBOSE][07/24/2023 12:45:17]: #1: updateCall, userId:360890854 isOutgoing:true state:CallStatePending {
  isCreated = true
  isReceived = true
}

[VOIP][VERBOSE][07/24/2023 12:45:24]: #1: updateCall, userId:360890854 isOutgoing:true state:CallStateExchangingKeys {
}

[VOIP][VERBOSE][07/24/2023 12:45:24]: #1: updateCall, userId:360890854 isOutgoing:true state:CallStateReady {
  protocol = CallProtocol {
    udpP2p = true
    udpReflector = true
    minLayer = 65
    maxLayer = 92
    libraryVersions = vector[1] {
      "8.0.0"
    }
  }
  servers = vector[6] {
    CallServer {
      id = 6014488021368
      ipAddress = "91.108.9.120"
      ipv6Address = "2001:67c:4e8:f102:7:0:285:708"
      port = 1400
      type = CallServerTypeWebrtc {
        username = "1690213525:90bb5b29180629c601"
        password = "0hBFbRVFPm+sRJuL7dFZsj/bWsU="
        supportsTurn = true
        supportsStun = true
      }
    }
    CallServer {
      id = 6014488022309
      ipAddress = "91.108.13.37"
      ipv6Address = "2001:b28:f23d:f101:2:0:116:915"
      port = 1400
      type = CallServerTypeWebrtc {
        username = "1690213525:90bb5b29180629c601"
        password = "0hBFbRVFPm+sRJuL7dFZsj/bWsU="
        supportsTurn = true
        supportsStun = true
      }
    }
    CallServer {
      id = 6014488023317
      ipAddress = "91.108.17.21"
      ipv6Address = "2001:b28:f23f:f105:1:0:861:905"
      port = 1400
      type = CallServerTypeWebrtc {
        username = "1690213525:90bb5b29180629c601"
        password = "0hBFbRVFPm+sRJuL7dFZsj/bWsU="
        supportsTurn = true
        supportsStun = true
      }
    }
    CallServer {
      id = 2574219218195
      ipAddress = "91.108.13.19"
      ipv6Address = "2001:b28:f23d:f101:1:0:111:303"
      port = 599
      type = CallServerTypeTelegramReflector {
        peerTag = bytes [16] { 5A 51 DB 16 FB 4C 72 16 29 CA EC 16 CD 1B 05 D0 }
        isTcp = false
      }
    }
    CallServer {
      id = 2574219217226
      ipAddress = "91.108.9.74"
      ipv6Address = "2001:67c:4e8:f102:4:0:285:10"
      port = 599
      type = CallServerTypeTelegramReflector {
        peerTag = bytes [16] { 5A 51 DB 16 FB 4C 72 16 29 CA EC 16 CD 1B 05 D0 }
        isTcp = false
      }
    }
    CallServer {
      id = 2574219219218
      ipAddress = "91.108.17.18"
      ipv6Address = "2001:b28:f23f:f105:1:0:861:902"
      port = 599
      type = CallServerTypeTelegramReflector {
        peerTag = bytes [16] { 5A 51 DB 16 FB 4C 72 16 29 CA EC 16 CD 1B 05 D0 }
        isTcp = false
      }
    }
  }
  config = "{"enable_vp8_encoder":true,"enable_vp8_decoder":true,"enable_vp9_encoder":true,"enable_vp9_decoder":true,"enable_h265_encoder":true,"enable_h265_decoder":true,"enable_h264_encoder":true,"enable_h264_decoder":true,"audio_frame_size":60,"jitter_min_delay_60":2,"jitter_max_delay_60":10,"jitter_max_slots_60":20,"jitter_losses_to_reset":20,"jitter_resync_threshold":0.5,"audio_congestion_window":1024,"audio_max_bitrate":20000,"audio_max_bitrate_edge":16000,"audio_max_bitrate_gprs":8000,"audio_max_bitrate_saving":8000,"audio_init_bitrate":16000,"audio_init_bitrate_edge":8000,"audio_init_bitrate_gprs":8000,"audio_init_bitrate_saving":8000,"audio_bitrate_step_incr":1000,"audio_bitrate_step_decr":1000,"use_system_ns":true,"use_system_aec":true,"force_tcp":false,"jitter_initial_delay_60":2,"adsp_good_impls":"(Qualcomm Fluence)","bad_call_rating":true,"use_ios_vpio_agc":false,"use_tcp":false,"audio_medium_fec_bitrate":20000,"audio_medium_fec_multiplier":0.1,"audio_strong_fec_bitrate":7000}"
  encryptionKey = bytes [256] { 5D 15 C2 5A BF C1 73 F3 9C 1A C0 37 B0 08 07 29 07 26 6E 2B 96 0C C4 6F 90 7C 16 34 1A 94 B8 FA 07 1A FD B6 08 54 08 72 62 AD 08 A8 F8 7D E6 8E AB 82 52 D6 24 72 6A 82 37 F9 7B B2 D7 04 2E AD ...}
  emojis = vector[4] {
    "��"
    "⛽"
    "��"
    "��"
  }
  allowP2p = true
}

====== CHECKPOINT 07/24/2023 12:45:41 ======
App: 0.25.10.1641-armeabi-v7a
SDK: 16 (Jelly Bean), NDK: 16 (armv7l)
Device: samsung SM-T211
Fingerprint: samsung/lt023gzs/lt023g:4.1.2/JZO54K/T211ZSANJ3:user/release-keys
Screen: 1024x600 (1.000000)
[APP][INFO][07/24/2023 12:45:41]: Opened database in 32ms
[APP][INFO][07/24/2023 12:45:41]: ==== INITIALIZATION STARTED IN 265MS ===
Manufacturer: samsung, Product: lt023gzs
[APP][INFO][07/24/2023 12:45:41]: readAccountConfig binlogSize:50
[APP][INFO][07/24/2023 12:45:41]: readAccountConfig finished, accountNum:2 in 2ms, preferredAccountId:0
[APP][WARN][07/24/2023 12:45:41]: sendTGConnectionType type:1 isOnline:true inBackground:true this.isOnline:true
[APP][INFO][07/24/2023 12:45:41]: ==== INITIALIZATION FINISHED IN 234ms ===
[FCM][ERROR][07/24/2023 12:45:52]: Failed to retrieve push token
=== Stack Trace Dump ===
java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:106)
	at y7.k.run(SourceFile:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at pd.r.m(SourceFile:30)
	at pd.r.a(SourceFile:62)
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:49)
	... 10 more
Caused by: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	... 4 more

=== Cause #1 ===
java.io.IOException: MISSING_INSTANCEID_SERVICE
java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at pd.r.m(SourceFile:30)
	at pd.r.a(SourceFile:62)
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:49)
	at y7.k.run(SourceFile:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	... 4 more

=== Cause #2 ===
MISSING_INSTANCEID_SERVICE
java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)

[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.listeners -> 1ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.cache -> 38ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.emoji -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.reaction -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.genericReactionEffects -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.filesManager -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.statusManager -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.contactManager -> 1ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.quickAckManager -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.settingsManager -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.wallpaperManager -> 0ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.notificationManager -> 64ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.fileGenerationManager -> 44ms
[APP][VERBOSE][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.applicationConfig -> 2ms
[APP][INFO][07/24/2023 12:47:44]: Creating TDLib client, hasInstance:false, accountId:0, debug:false, wasPaused:false
[APP][INFO][07/24/2023 12:47:44]: INITIALIZATION: Tdlib.newClient() -> 124ms
[APP][VERBOSE][07/24/2023 12:47:45]: INITIALIZATION: TDLIB FINISHED INITIALIZATION & SENT VALID AUTH STATE IN 350MS, WASTED: 6MS
[APP][INFO][07/24/2023 12:47:45]: Performing account startup for accountId:0, isAfterRestart:false
[APP][INFO][07/24/2023 12:47:45]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:47:45]: MainActivity.onCreate
[APP][INFO][07/24/2023 12:47:46]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:47:46]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:47:46]: MainActivity.onResume
[APP][INFO][07/24/2023 12:47:46]: accountId:0 refreshUiPaused -> false
[FCM][ERROR][07/24/2023 12:47:58]: Failed to retrieve push token
=== Stack Trace Dump ===
java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:106)
	at y7.k.run(SourceFile:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at pd.r.m(SourceFile:30)
	at pd.r.a(SourceFile:62)
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:49)
	... 10 more
Caused by: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	... 4 more

=== Cause #1 ===
java.io.IOException: MISSING_INSTANCEID_SERVICE
java.util.concurrent.ExecutionException: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at pd.r.m(SourceFile:30)
	at pd.r.a(SourceFile:62)
	at com.google.firebase.messaging.FirebaseMessaging.a(SourceFile:49)
	at y7.k.run(SourceFile:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	... 4 more

=== Cause #2 ===
MISSING_INSTANCEID_SERVICE
java.io.IOException: MISSING_INSTANCEID_SERVICE
	at l5.c.a(SourceFile:124)
	at j7.a.o(SourceFile:258)
	at y7.r.v(SourceFile:129)
	at androidx.appcompat.widget.i.run(SourceFile:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at f3.f.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:856)

[APP][INFO][07/24/2023 12:48:55]: accountId:0 refreshUiPaused -> true
[APP][INFO][07/24/2023 12:48:55]: SetOnline accountId:0 -> false
[APP][INFO][07/24/2023 12:48:55]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:48:55]: MainActivity.onPause
[APP][INFO][07/24/2023 12:49:21]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:49:21]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:49:21]: MainActivity.onResume
[APP][INFO][07/24/2023 12:49:21]: accountId:0 refreshUiPaused -> false
[APP][INFO][07/24/2023 12:49:33]: accountId:0 refreshUiPaused -> true
[APP][INFO][07/24/2023 12:49:33]: SetOnline accountId:0 -> false
[APP][INFO][07/24/2023 12:49:33]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:49:33]: MainActivity.onPause
[APP][INFO][07/24/2023 12:49:59]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:49:59]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:49:59]: MainActivity.onResume
[APP][INFO][07/24/2023 12:50:00]: accountId:0 refreshUiPaused -> false
[APP][INFO][07/24/2023 12:50:09]: accountId:0 refreshUiPaused -> true
[APP][INFO][07/24/2023 12:50:09]: SetOnline accountId:0 -> false
[APP][INFO][07/24/2023 12:50:09]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:50:10]: MainActivity.onPause
[APP][INFO][07/24/2023 12:50:59]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:50:59]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:50:59]: MainActivity.onResume
[APP][INFO][07/24/2023 12:50:59]: accountId:0 refreshUiPaused -> false
[APP][INFO][07/24/2023 12:51:07]: accountId:0 refreshUiPaused -> true
[APP][INFO][07/24/2023 12:51:07]: SetOnline accountId:0 -> false
[APP][INFO][07/24/2023 12:51:07]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:51:07]: MainActivity.onPause
[APP][INFO][07/24/2023 12:51:16]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:51:16]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:51:16]: MainActivity.onResume
[APP][INFO][07/24/2023 12:51:17]: accountId:0 refreshUiPaused -> false
[APP][INFO][07/24/2023 12:54:41]: accountId:0 refreshUiPaused -> true
[APP][INFO][07/24/2023 12:54:41]: SetOnline accountId:0 -> false
[APP][INFO][07/24/2023 12:54:41]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:54:41]: MainActivity.onPause
[APP][INFO][07/24/2023 12:54:41]: SetOnline accountId:0 -> true
[APP][INFO][07/24/2023 12:54:41]: System night mode, selected:1(no), applying:false, managerMode:0(unspecified), configMode:1(no), isNight:false
[APP][INFO][07/24/2023 12:54:41]: MainActivity.onResume
[APP][INFO][07/24/2023 12:54:42]: accountId:0 refreshUiPaused -> false

**Comment by vkryl** [comment]
Можете, пожалуйста, прочитать предыдущий комментарий?

> В Settings — зажать версию приложения — Application Logs — Testing Utilities — tgcalls versions методом исключения перечислите все версии списком, которые работают / не работают.

Логи не нужны.

**Comment by NektoNektovich** [comment]
> Можете, пожалуйста, прочитать предыдущий комментарий?
> 
> > В Settings — зажать версию приложения — Application Logs — Testing Utilities — tgcalls versions методом исключения перечислите все версии списком, которые работают / не работают.
> 
> Логи не нужны. Нужно найти версии библиотек, которые работают.

хорошо. tgx 0.25.10.1645 arm7a beta
tgcalls versions:
2.4.4 - звонок работает, ок
2.7.7 - звонок не работает (нет соединения, только появился счетчик времени разговора 00:01 и застыл), и tgx падает
5.0.0 - звонок не работает (нет соединения, только появился счетчик времени разговора 00:01 и застыл), и tgx падает
6.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
7.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
8.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
9.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
10.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
11.0.0 - звонок не работает (нет соединения, даже не появился счетчик времени звонка), и tgx падает
tgcalls все версии не отмечены - звонок работает, ок

прошу прощения, что не сразу понял, что именно надо было сделать, не разобрался

**Comment by NektoNektovich** [comment]
Полюбопытствовал ещё и tgcalls options, вот бы эту настройку сделать постоянной 🤗 мне из трёх опций хотелось бы оставить включенной только амплитудный нормалайзер, что для голосовго звука весьма на пользу в отличии от музыки 🤓

**Comment by NektoNektovich** [comment]
Сейчас поставил обнову 0.25.10.1647 arm7 на андроид 4.1.2 и - приложение telegram x остановлено 😐

**Comment by vkryl** [comment]
tgcalls на Android версиях ниже 4.4 больше не используется, звонок должен работать. Если какие-то другие проблемы, то нужны логи ошибок (файл crash.*, либо Android Bug Report).

**Comment by vkryl** [comment]
Приложение просто перестало запускаться? Часть пользователей на 4.x жалуется, это не связано со звонками. https://t.me/tgandroidtests/254343 эта сборка запускается?

**Comment by NektoNektovich** [comment]
Да, сборка 0.25.10.1648 arm7 запустилась и звонок теперь работает! 🤗
большое спасибо! 👍☺️

пятница, 4 августа 2023 г. пользователь Vyacheslav ***@***.***>
написал:
> Приложение просто перестало запускаться? Часть пользователей на 4.x
жалуется, это не связано со звонками. https://t.me/tgandroidtests/254343
эта сборка запускается?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/OEWwNcJ7U0N4amzqkH6zVZsTZfIiG0zE1fxQqzE8WguaeF66_su-eGy1opDZIY4QuvdvaiAdQtaY4xtLW50-It_ROcgTQdbIzP4JMUS8QPz2rg88cA3ZWwnER4DF1gIIpO46pw0W7czWYeHj41fGAIfNtJEMHvZAXopKNGeX6VaXomC9dvglfxl0SYgc0dkKQP0l7bWrtZbIDwuIC3Ulggka7WFncLE-mUEV2T8j-6k42sbIuQ=s0-d-e1-ft#https://github.com/notifications/beacon/AMZDE6ADZ53L5HYZOKRUISDXTQM5VA5CNFSM6AAAAAA2UUQCHSWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTDHEZRG.gif>Message
ID: ***@***.***>

**Comment by NektoNektovich** [comment]
Сегодня и на днях созванивался, и, вновь собеседники говорят, что меня плохо слышно - тихо, хотя у них громкость разговорного динамика на полную 😒 рядом вацап и при звонках в нём и меня хорошо слышат и я собеседника. Сделайте пожалуйста, чтобы звук с микрофона в tgx был громче на 4 или 5дб 🙏 не знаю, может это встроенный в tgx auto gain control настроен с параметром занижать громкость, вместо усиления? 🤔
