### ISSUE TITLE
Error on saving GIF,  "#400: CHAT_FORWARDS_RESTRICTED"

### ISSUE THREAD

**Issue by Bub0** [TGX-Android/Telegram-X#423]
1. Telegram X 0.25.10.1645-arm64-v8a (c214f174)
TDLib: 1.8.14 (tdlib/td@1886bcf)
Android: 13 (33)
Device: samsung samsung SM-S908B (TP1A.220624.014.S908BXXS6CWF6)
Screen: 2106x1080 (density: 2.8125, fps: 24.0)
Build: `samsung/b0sxeea/b0s:13/TP1A.220624.014/S908BXXS6CWF6:user/release-keys`
Package: org.thunderdog.challegram
Locale: sv_SE (app: sv)
Installer: Google Play
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

2. https://t.me/liveukraine_media/12232

3. https://ibb.co/xSZPLhZ

4. Error on saving GIF, 
"#400: CHAT_FORWARDS_RESTRICTED" 

5. Google Play Store
![Screenshot_20230802_174904_Telegram X](https://github.com/TGX-Android/Telegram-X/assets/40185468/8e14046e-a2ab-4cbe-9a0c-43ba8b7f3bad)

**Comment by Sajilck** [comment]
Can you test with latest version

**Comment by Bub0** [comment]
> Can you test with latest version

Forgot about this hehe.
No issues now! Thanks. 🙂
