### ISSUE TITLE
Problem saving album

### ISSUE THREAD

**Issue by wzry2580** [TGX-Android/Telegram-X#428]
I hope to support batch saving of album pictures in the future. The official version can support your version, can you?

**Comment by wzry2580** [comment]
I hope to support batch saving of album pictures in the future, and the official version can support it


 You can also support this version, can you?

**Comment by wzry2580** [comment]
I hope to support batch saving of album pictures in the future, and the official version can support it


 You can also support this version, can you?

**Comment by wzry2580** [comment]
It’s just a Google service message push reminder, can it be turned off, because the mobile phone does not support the use of Google services, so the reminder is a bit conspicuous, can it be turned off?

**Comment by vkryl** [comment]
There is a batch save to gallery already available. Just make sure all photos are downloaded and tap on a message, then tap "Save X photos/videos/etc".
