### ISSUE TITLE
Bug in proxy liat page

### ISSUE THREAD

**Issue by Esmaeilds** [TGX-Android/Telegram-X#438]
When we go to the proxy page after adding a proxy, we see an option (hide error details) at the top of the page after clicking on the more icon, but after selecting a proxy, we see two options. In fact, the option (reorder by ping) is added.
This option has no special logic, sometimes it is seen, sometimes not

Phone:
Galaxy A52s 5G
SM-A528B/DS

Follow Steps:
- add proxy
- disable proxy
- go to proxy list page
- click on more icon
- check choice in modal (hide error details)
- now click on one proxy and enable it
- click on more icon
- check choice in modal (hide error details) + (reorder by ping)

![Screenshot_20230828_081411_Telegram X](https://github.com/TGX-Android/Telegram-X/assets/79710927/135d675d-15c5-4bdd-a25b-6d68bfc9be1c)
![Screenshot_20230828_082728_Telegram X](https://github.com/TGX-Android/Telegram-X/assets/79710927/20977603-d5fb-48c1-824b-9cbf6666f313)

**Comment by vkryl** [comment]
It does exactly what it says — reorders by ping. When the list is already sorted, it isn't shown.
