### ISSUE TITLE
[Bug] Unable to send messages to some contacts

### ISSUE THREAD

**Issue by mdziczkowski** [TGX-Android/Telegram-X#441]
## Apply to:
- *OS*: Android 13
- *Telegram X version*: 0.25.11.1651-arm64-v8a

## Issue description:

While attempting to send a message to a person on my contact list, I recieve every time following error message (not sure if it got correctly translated):

`
Delivery failed. Currently, you can only interact with each other's contacts.
`

*Note*:

- none of sides are on another's block list
- there aren't set any privacy settings with could block the contact

**Comment by vkryl** [comment]
There's nothing can be done, as this is handled by server. If other person will add you as contact, you should be able to start messaging them.

**Comment by mdziczkowski** [comment]
The thing is that me and the other person are already contacts
