### ISSUE TITLE
[Bugs] Share Problem

### ISSUE THREAD

**Issue by SamiulSP71** [TGX-Android/Telegram-X#455]
When I am trying to share a photo, link, videos, I mean anything from other apps like gallery, youtube, Instagram, by common share button, and where shows which apps I can share to, like telegram, whatsapp, messager.
The problem is, after first share, whatever I try to share again, it sends same file again and again. Untill I force stop telegram x and reopen it.

**Comment by vkryl** [comment]
Please read carefully the [issue guide](https://github.com/TGX-Android/Telegram-X/blob/main/docs/ISSUE_TEMPLATE.md) and submit the result of the `Copy Report Details` here.
