### ISSUE TITLE
Account banning issue 

### ISSUE THREAD

**Issue by MAAB-FW** [TGX-Android/Telegram-X#464]
Many people in our Bangladesh(+880) got their Telegram ID banned just because they login to Telegram X. Even new account opened with Telegram X got banned. Account ban within 10-15 seconds of login or account opening.

This is a major technical problem. Please fix it and get the banned account back.
I have proof of this happening to many other people.
![image](https://github.com/TGX-Android/Telegram-X/assets/128562152/dd4a8ba1-e506-4c59-b9a3-bdbc25b4e3fa)

**Comment by vkryl** [comment]
This isn't relevant to Telegram X — the ban process is controlled by Telegram servers, not the Telegram X app (or any other Telegram client).

Submit the report to recover@telegram.org, which must include:
- phone number
- time and date when you signed up / logged in
- time and date when you were banned
- your location (region) and Internet Service Provider
- information about VPN, if it was used.
