### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by Wily96** [TGX-Android/Telegram-X#470]
You should also get your employer (if you work as a programmer) or school, 
 if any, to sign a "copyright disclaimer" for the program, if necessary. 
 For more information on this, and how to apply and follow the GNU GPL, see 
 <https://www.gnu.org/licenses/>. 
  
   The GNU General Public License does not permit incorporating your program 
 into proprietary programs.  If your program is a subroutine library, you 
 may consider it more useful to permit linking proprietary applications with 
 the library.  If this is what you want to do, use the GNU Lesser General 
 Public License instead of this License.  But first, please read 
 <https://www.gnu.org/licenses/why-not-lgpl.html>.

**Comment by vkryl** [comment]
Components licensed by other types of licenses can be found in https://github.com/TGX-Android.
