### ISSUE TITLE
Issue #322 is back in 1660

### ISSUE THREAD

**Issue by Makh-b** [TGX-Android/Telegram-X#473]
Messages marked as "read" INSTANTLY when using preview.

https://github.com/TGX-Android/Telegram-X/assets/66366624/779ddcf3-91e9-4d10-9bd7-ddc3e91cd378

**Comment by smiba** [comment]
Can confirm, suffering from this as well

**Comment by smiba** [comment]
@vkryl Any chance you could look into this? It's an annoying regression that probably does harm to a lot of workflows.

Unfortunately society cares a lot about read receipts and accidentally putting a message on read can have negative consequences 😬

**Comment by vkryl** [comment]
Already fixed in 5c1439f
