### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by PavanLuca** [TGX-Android/Telegram-X#474]
Always crashing when launching it since the latest beta update.
![Screenshot_2023-10-14-04-39-33](https://github.com/TGX-Android/Telegram-X/assets/123581658/f6732c19-8c7e-4847-8102-876ec1d14e15)
![Screenshot_2023-10-14-04-39-59](https://github.com/TGX-Android/Telegram-X/assets/123581658/de1cd3cc-a618-417f-959e-ff54e2bf0985)
![Screenshot_2023-10-14-04-40-37](https://github.com/TGX-Android/Telegram-X/assets/123581658/0f36fc08-da77-4064-a09e-55f0b7ff0e99)
![Screenshot_2023-10-14-04-40-47](https://github.com/TGX-Android/Telegram-X/assets/123581658/95c6ae1e-8bc5-45bd-98c9-53029586a0cc)

**Comment by vkryl** [comment]
Can you send a crash log by extracting it via System Bug Report or any logcat tool?

**Comment by vkryl** [comment]
Should probably be possible to copy stack trace by pressing the corner button on the right of "Stack trace" button

**Comment by PavanLuca** [comment]
![Screenshot_2023-10-14-17-13-49](https://github.com/TGX-Android/Telegram-X/assets/123581658/68921543-194d-4dfd-bbda-34f30782d3d8)
![Screenshot_2023-10-14-17-13-59](https://github.com/TGX-Android/Telegram-X/assets/123581658/e24bfc68-b20c-475a-b308-98762b97c084)

**Comment by PavanLuca** [comment]
I updated it, now it works, thanks 😀🎉.

**Comment by vkryl** [comment]
Thank you very much for the full stack trace. Perfectly, this should be properly investigated reported to Android Gradle Plugin developers, if corresponding issue isn't created already, as simply downgrading from `8.1.x` to `8.0.2` version resolved the issue (c552fbb). If anyone sees this comment and has spare time and resources to dig dive into this issue to help Telegram X, AGP and Android 4.x users - please don't hesitate to do so.
