### ISSUE TITLE
When will the "chats marked as read in preview mode" be fixed ?

### ISSUE THREAD

**Issue by mathieuthibault** [TGX-Android/Telegram-X#475]
Hi all,

I saw that in 1660, the "messages marked as read when using preview" issue is back. On another thread (https://github.com/TGX-Android/Telegram-X/issues/473), the issue has been marked as fixed and closed by @vkryl.

But can we know when it will be available again ? Any idea when the next update (including that fix) will be published ?
Many of us can't use Telegram properly until it gets fixed, as this feature is very usefull to us.

Thanks for the great work!

Regards.

**Comment by Sajilck** [comment]
As mentioned in the #473 it is fixed with https://github.com/TGX-Android/Telegram-X/commit/5c1439fd24859d8048572d049ee42eb349d57577 

This fix will be available in next beta.

Note: A beta app is expected to have bugs, no need to open issues again when it is already reported
