### ISSUE TITLE
`Save on gallery` makes the app crash

### ISSUE THREAD

**Issue by PavanLuca** [TGX-Android/Telegram-X#480]
Crash when saving pictures to phone gallery.
![Screenshot_2023-10-18-10-19-05](https://github.com/TGX-Android/Telegram-X/assets/123581658/0b75231c-9770-42c4-9a0e-d413e26b8fb9)
Effectively, the pictures were saved anyway. Moreover, this issue happened only once, on the next session it never happened again.

**Comment by vkryl** [comment]
Should be already fixed.
