### ISSUE TITLE
Missing multiple selection number

### ISSUE THREAD

**Issue by PavanLuca** [TGX-Android/Telegram-X#482]
3?
![Screenshot_2023-10-18-20-40-54](https://github.com/TGX-Android/Telegram-X/assets/123581658/6b572d5d-1313-4c2b-a05f-26dd62c5d6fd)

**Comment by vkryl** [comment]
You can open the media viewer, tap the counter and see which image is the 3rd.

**Comment by PavanLuca** [comment]
Yes, I know, the problem was simply that Telegram X didn't load the circle 3, as you can see on my screenshot I selected the second picture as third attachment for the message but 3 was missing. I tried again the multiple selection but this issue didn't happen again.

**Comment by vkryl** [comment]
You could have accidentally selected media that is below the visible part of the grid.
