### ISSUE TITLE
Beta version is constantly crashing

### ISSUE THREAD

**Issue by PavanLuca** [TGX-Android/Telegram-X#484]
Recently the beta version started crashing for different reasons and I realized that the stack trace is always the same, when it crashed some seconds after that I sent a message containing a Facebook link, when phone charge was interrupted, once the phone connected to my Wi-Fi some seconds after that I opened the app while being offline and when I saved a picture.
![Screenshot_2023-10-19-10-57-35](https://github.com/TGX-Android/Telegram-X/assets/123581658/e5075854-79a0-494e-b865-beeba9a7be95)
By the way, whenever a crash happened I sent the feedback to Google so I suppose they'll send it to you in the meantime.

**Comment by vkryl** [comment]
Thank you for these provided details. I will close this issue, as it has exactly the same stack trace as #480. If you find any other cases that cause a crash with the same stack trace, you can use the existing issue.

**Comment by PavanLuca** [comment]
Got it, thanks. But beyond the stack trace is there a specific log section or entries that I can post to give you more details of the crashes that may happen?
