### ISSUE TITLE
> Going to resolve all conflicts caused by changes on the `main` branch and publish an updated version in [@tgx_prs](https://t.me/tgx_prs) soon.

### ISSUE THREAD

**Issue by Private360** [TGX-Android/Telegram-X#485]
> Going to resolve all conflicts caused by changes on the `main` branch and publish an updated version in [@tgx_prs](https://t.me/tgx_prs) soon.

@vkryl The "Archive/Unarchive" button is missing in folders. (in the Chat Preview, and in the three-dot menu when selecting multiple chats)

Also please add archived chats settings to the "Archive" folder. (These settings are accessible in official Telegram in the three-dot menu of archived chats)

_Originally posted by @sepehrbrj in https://github.com/TGX-Android/Telegram-X/issues/297#issuecomment-1697220969_

**Comment by vkryl** [comment]
Archive settings are already available in beta.
