### ISSUE TITLE
Unsupported message 

### ISSUE THREAD

**Issue by notengo13** [TGX-Android/Telegram-X#490]
I see this message in various groups.
Unsupported message. 
![Screenshot_20231029_214649_edit_119782714173908](https://github.com/TGX-Android/Telegram-X/assets/142510815/7c8bd060-e01a-40b4-b29f-799f46cd2f4b)

**Comment by notengo13** [comment]
![Screenshot_20231029_215054](https://github.com/TGX-Android/Telegram-X/assets/142510815/54c80484-cc0e-442b-a96c-480a4293f40e)

**Comment by vkryl** [comment]
This feature depends on the API that yet isn't implemented in TDLib. Once it will be available there, implementing viewing such messages will be the top-1 priority. Unfortunately, can't provide any ETAs, can only say it's top priority in both TDLib and Telegram X side, and will arrive in public beta as soon as possible (in stable – after bug fixes based on beta reports).

**Comment by vkryl** [comment]
Closing issue as it is missing feature.

You can watch for updates in commit messages of [TDLib](https://github.com/tdlib/td) and this repository, or simply subscribe to [@tgx_dev](https://t.me/tgx_dev).
