### ISSUE TITLE
CLEAR STORAGE USAGE

### ISSUE THREAD

**Issue by victorkhai** [TGX-Android/Telegram-X#511]
I'M UPDATING TO Telegram X **0.26.1.1665-arm64-v8a & in this version CLEARING STORAGE USAGE take longer than usual previous app, 
![Screenshot_2023-11-29-18-57-07-52_1149b56b894fd37d9a6fe46f85aae740](https://github.com/TGX-Android/Telegram-X/assets/115313186/769026b1-39a8-49de-9e3d-1341ac066ed8) like see I've used only around 1 gb and i want to clear that but it took around 3 to 4 minutes wait time 🥺😥 and very frustrating.HOPE U FIX THIS IN UPCOMING UPDATE.Thanks in Advance 🙂☺️.

Telegram X 0.26.1.1665-arm64-v8a (f7fd8f71c)
PRs: #486 (61feab9df)
TDLib: 1.8.20 (tdlib/td@dd77e46)
Android: Pie (28)
Device: OPPO OPPO CPH2083 (CPH2083EX_11_A.67)
Screen: 1376x720 (density: 2.0, fps: 60.15)
Build: `OPPO/CPH2083/OP4BFB:9/PPR1.180610.011/1642488389:user/release-keys`
Package: org.thunderdog.challegram
Locale: en_US (app: en)
Installer: Google Play
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

#victor_khai

**Comment by vkryl** [comment]
What was the last version it was working faster?

**Comment by victorkhai** [comment]
Maybe
0.25.11.1652-ARM64-V8A
