### ISSUE TITLE
Calls and Cicle record Crash

### ISSUE THREAD

**Issue by DeadLiner85** [TGX-Android/Telegram-X#514]
## Issue: Beta Telegram X Calls and Cicle record Crash

### Problem Description

After updating the two beta versions, any call or cicle recording causes the app to crash. For a call, both an outgoing and an incoming call. Viewing a cicle recorded from another device or by an interlocutor does not cause crashes.

### Environment Information

- Application Version: [Telegram X 0.26.2.1667-arm64-v8a (9cf2acfb)]
- Operating System: [Android: 10 (29)]

### Logs

The link contains 4 log files for circle and call crash. also Report Details
[Cloud link] (https://cloud.darx.zip/s/tg_crash_report)
### Reproducibility

- [x] Reproduces always
- [ ] Reproduces randomly

### Priority

- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

Thank you for your attention to this matter.

**Comment by vkryl** [comment]
Should be both resolved in the 1669. It happens only when animations are disabled on system level.
