### ISSUE TITLE
New Account Creating/Imprting get banned

### ISSUE THREAD

**Issue by samad3w** [TGX-Android/Telegram-X#529]
I just created new account using Telegram X , it's got banned in few minutes.

I also imported new accounts and it also got banned .
I tried many times number getting banned.

I like Telegram X,
Is there any solution ???

![Screenshot_2024-01-07-22-29-13-556_org thunderdog challegram-edit](https://github.com/TGX-Android/Telegram-X/assets/151950726/393c3512-94fe-4a1c-9713-6519fdab7c30)

**Comment by vkryl** [comment]
Have you tried pressing the "Contact us" and did you send there an email with the phone number you are entering? If yes, how long ago? The ban process is handled by servers fully, there's nothing in particular Telegram X as a client app could do.

**Comment by samad3w** [comment]
> Have you tried pressing the "Contact us" and did you send there an email with the phone number you are entering? If yes, how long ago? The ban process is handled by servers fully, there's nothing in particular Telegram X as a client app could do.

My  point is not my id got banned.
My main point is that I tried many phone , new account creating/importing (login),
All got banned instantly ,
I repeat all is new account.

I didn't face in others apps

**Comment by vkryl** [comment]
@samad3w there's nothing can be done on Telegram X side, as it doesn't handle phone number banning in any way. Try reporting via "Contact us" link and getting help there, as that's the only way for it.

**Comment by satishcode123** [comment]
Even just now I created my newly Account on tg with different no. On telegram X and it just got immediately banned with of no reason

**Comment by SamRezaXYZ** [comment]
> Even just now I created my newly Account on tg with different no. On telegram X and it just got immediately banned with of no reason

Try to avoid new account on TGX.
minimum account age have to be 4 months plus
