### ISSUE TITLE
Can't turn off the data saver mode

### ISSUE THREAD

**Issue by noelra** [TGX-Android/Telegram-X#532]
I can't turn off the data saver mode in the app settings. Turn on automatically option is set to never, background data usage and unrestricted internet access is also enabled in device settings.

**Comment by vkryl** [comment]
1. Always include `Copy report details` when reporting issues.
2. It has to be something with your mobile data settings (`Metered network` toggle, etc). [Here](https://github.com/TGX-Android/Telegram-X/blob/0c9f7005733dc8ed27c963dd92dc1cbbfdd56db1/app/src/main/java/org/thunderdog/challegram/core/WatchDog.java#L296) is the condition that is used to determine that, and there are no issues, and no change in reports number (it always has to do with device settings).
