### ISSUE TITLE
SMS code problem/Main server

### ISSUE THREAD

**Issue by TannicArcher** [TGX-Android/Telegram-X#534]
The problem is this
It all started with one launch of the application and in the end I had to reinstall it, in the end I launch and enter the number but the code comes to the device that is already authorized, that is, my main phone and I click on receive an SMS code, nothing happens from the word I tried the same call and so it continues 3 days connection very good with mobile operator
I am using the latest version as of January 4th
I in Ukraine
I wrote to support via email and Twitter and no response for more than 3 days.

There may be a problem with your servers or its configuration
Also look at the Downradar site there are some complaining about crashes

**Comment by vkryl** [comment]
What is your specific region, phone country code and operator? Have you tried describing your issue and phone number to `sms at telegram.org` or did you use some other email?

**Comment by TannicArcher** [comment]
I wrote about what happened here at support[at]telegram.org and on Twitter smstelegram

**Comment by TannicArcher** [comment]
It turns out that my “very good” mobile operator blocked SMS from Telegram as spam, now everything works
Thanks for support
