### ISSUE TITLE
Custom emoji statuses don't scale properly on low resolution displays

### ISSUE THREAD

**Issue by matinlunaire** [TGX-Android/Telegram-X#539]
Still (not animated) emoji statuses appear blurry once they've loaded on low res displays (480x800 in the example below). Happens everywhere they're used (when viewing profiles, next to name in chats, during calls).

With a fairly slow internet connection, it's sometimes possible to see those icons the way they're intended to appear for a brief moment, until they finish loading in their full resolution and the blurry downscaling is applied (see the demo video below - pay attention to the status icon as it loads!). Once loaded, they stay like this forever (until cache is cleared).

Link to the emoji pack used: https://t.me/addemoji/win95i (but it happens with any, really)

![Screenshot_20240116-181725~2](https://github.com/TGX-Android/Telegram-X/assets/109166520/587cc1e4-e054-483a-b677-8b029dddd8ff)
![Video](https://github.com/TGX-Android/Telegram-X/assets/109166520/f3df48b2-bba6-4e35-bd72-7d0ba266c8b7)

Telegram X 0.26.3.1674-armeabi-v7a (8b30d0fe)
TDLib: 1.8.23 (tdlib/td@d963044)
Android: Marshmallow (23)
Device: samsung samsung SM-J106F (MMB29Q.J106FJVU0ARE1)
Screen: 800x480 (density: 1.5, fps: 60.001)
Build: `samsung/j1miniveltejv/j1minivelte:6.0.1/MMB29Q/J106FJVU0ARE1:user/release-keys`
Package: org.thunderdog.challegram
Locale: en_US (app: en)
Installer: Google Play
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Comment by vkryl** [comment]
Thank you for the well-detailed report. Please report if the issue doesn't go away in the next beta version (`1680`).
