### ISSUE TITLE
False-positive emulator detection warning on Asus `ASUS_I005DA`

### ISSUE THREAD

**Issue by MrRightDongYuJie1314** [TGX-Android/Telegram-X#546]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: Asus `ASUS_I005DA`
Product: `ASUS_I005DA`
Device: `ASUS_I005DA`
Hardware: `qcom`

**The app version I am using:**

Telegram X 0.26.4.1681-arm64-v8a (emulator) (f090fdb8)
PRs: #543 (f33d846f)
TDLib: 1.8.23 (tdlib/td@09c6bad)
Android: Pie (28)
Device: Asus Asus ASUS_I005DA (Asus-user 9.0.0 20171130.276299 release-keys)
Screen: 2208x976 (density: 1.0, fps: 60.0)
Build: `Asus/Asus/ASUS_I005DA:9/mv-dev103041042:user/release-keys`
Package: org.thunderdog.challegram
Locale: zh_CN (app: en)
Installer: com.microvirt.download
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `a`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by vkryl** [comment]
Based on the details you provided, the app must be running via emulator on the PC, and detection result is correct. If you are running on a real ASUS phone, could you specify the brand name of your phone and record the video of Telegram X running on that phone & showing that prompt? Did you make any modifications to the system? Do you have any external devices connected to that phone? Or is that phone connected to the PC? Thank you.
