### ISSUE TITLE
False-positive emulator detection warning on vivo `V2238A`

### ISSUE THREAD

**Issue by ghost** [TGX-Android/Telegram-X#551]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: vivo `V2238A`
Product: `V2238A`
Device: `V2238A`
Hardware: `V2238A`

**The app version I am using:**

Telegram X 0.26.4.1681-arm64-v8a (emulator) (f090fdb8)
PRs: #543 (f33d846f)
TDLib: 1.8.23 (tdlib/td@09c6bad)
Android: 12L (32)
Device: vivo vivo V2238A (V417IR release-keys)
Screen: 1600x900 (density: 1.5, fps: 60.000004)
Build: `OnePlus/OnePlus8Pro/OnePlus8Pro:12/V417IR/2401251504:user/release-keys`
Package: org.thunderdog.challegram
Locale: zh_CN (app: en)
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `a`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by vkryl** [comment]
Can you please share more information about your specific device & setup?

1. Do you have your phone connected to the PC?
2. Are you trying to run Telegram X on a PC?
3. What software do you use for this purpose?
