### ISSUE TITLE
False-positive emulator detection warning on Xiaomi `2206122SC`

### ISSUE THREAD

**Issue by 285656** [TGX-Android/Telegram-X#562]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: Xiaomi `2206122SC`
Product: `2206122SC`
Device: `2206122SC`
Hardware: `2206122SC`

**The app version I am using:**

Telegram X 0.26.5.1687-universal (emulator) (903c5ed5)
PRs: #556 (fa45e7ce), #557 (c171d83c)
TDLib: 1.8.24 (tdlib/td@d79bd4b)
Android: 12L (32)
Device: Xiaomi Xiaomi 2206122SC (V417IR release-keys)
Screen: 1280x720 (density: 1.5, fps: 60.000004)
Build: `OnePlus/OnePlus8Pro/OnePlus8Pro:12/V417IR/2401041722:user/release-keys`
Package: org.thunderdog.challegram
Locale: zh_CN (app: en)
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `0xb`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by vkryl** [comment]
Do you have your device connected to a PC? If yes, try disconnecting first. If not, can you record a video of the prompt on your phone?
