### ISSUE TITLE
False-positive emulator detection warning on Xiaomi `MI 5s`

### ISSUE THREAD

**Issue by sarujansarujan** [TGX-Android/Telegram-X#569]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: Xiaomi `MI 5s`
Product: `capricorn`
Device: `capricorn`
Hardware: `cancro_overseas_x86_64`

**The app version I am using:**

Telegram X 0.26.5.1690-arm64-v8a (emulator) (e0bdca9a)
PRs: #567 (1fdae211)
TDLib: 1.8.25 (tdlib/td@d0ff90b)
Android: Marshmallow (23)
Device: Xiaomi Xiaomi MI 5s (V417IR release-keys)
Screen: 1024x576 (density: 1.2, fps: 60.000004)
Build: `OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447841200:user/release-keys`
Package: org.thunderdog.challegram
Locale: en_US (app: en)
Installer: mumu-vapi
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `0xb`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by vkryl** [comment]
Do you have any device connected to your phone?
