### ISSUE TITLE
Login and Banning Problem on Android

### ISSUE THREAD

**Issue by swaponboss22** [TGX-Android/Telegram-X#574]
### Description:
I encountered a recurring issue while attempting to login to Telegram X on my Android 10 device. Despite trying with multiple phone numbers, the application logs in successfully but immediately logs out automatically. Upon subsequent attempts to sign in, I receive a message indicating that the phone number has been banned. I can confirm that no violations of Telegram's rules or policies were knowingly committed.

### Steps to Reproduce:
1. Open Telegram X on an Android 10 device.
2. Attempt to login using multiple phone numbers.
3. Observe the application logging in successfully but then automatically logging out.
4. Upon trying to sign in again, receive a message stating that the phone number has been banned.

### Expected Behavior:
- The application should allow users to login without automatically logging them out.
- Phone numbers should not be banned without violating Telegram's rules or policies.

### Observed Behavior:
- The application logs users in but immediately logs them out, leading to a ban on the phone number.

### Additional Information:
- **Device:** Android 10
- **Telegram X Version:** (if available)
- This issue persists across multiple attempts and multiple phone numbers.
- No violations of Telegram's rules or policies were knowingly committed.
- Screenshots or videos can be provided upon request, with the app's language changed to English.
- APK source: (Google Play Store, Telegram Channels, etc.)

### Checklist:
- [x] Issue pertains to a bug.
- [x] Structure of the report follows the provided guidelines.
- [x] Report is in English.

---

Thank you for your attention to this matter. Your assistance in resolving this issue is greatly appreciated.

**Comment by vkryl** [comment]
Try contacting `recover@telegram.org`, describe your issue, and specify your phone number. There's nothing can be done on Telegram X side to affect this.

**Comment by samad3w** [comment]
> Try contacting `recover@telegram.org`, describe your issue, and specify your phone number. There's nothing can be done on Telegram X side to affect this.

It's happening all device, Only on TG X , other tg or  tg client didn't happen

**Comment by swaponboss22** [comment]
> > Try contacting `recover@telegram.org`, describe your issue, and specify your phone number. There's nothing can be done on Telegram X side to affect this.
> 
> It's happening all device, Only on TG X , other tg or tg client didn't happen

Yes. But they don't look forward to it.

**Comment by massXtrash** [comment]
> > > Try contacting `recover@telegram.org`, describe your issue, and specify your phone number. There's nothing can be done on Telegram X side to affect this.
> > 
> > 
> > It's happening all device, Only on TG X , other tg or tg client didn't happen
> 
> Yes. But they don't look forward to it.

Yea, it's already 1yrs+, there's reply always same
