### ISSUE TITLE
Notification of private message

### ISSUE THREAD

**Issue by PavanLuca** [TGX-Android/Telegram-X#579]
**Private** in Italian is **Privato**. Can be changed into **Messaggio privato** (**Private message**) for a better comprehension and being more specific.
![Screenshot_2023-09-29-13-58-09](https://github.com/TGX-Android/Telegram-X/assets/123581658/e9e516ae-97d3-41af-b795-d96bfe767006)

**Comment by Sajilck** [comment]
Please suggest to translations.telegram.org
