### ISSUE TITLE
I do not receive background notifications

### ISSUE THREAD

**Issue by 10Meisterbaelle** [TGX-Android/Telegram-X#588]
When the app is closed, I don't recieve notifications, even if battery optimization is disabled.

I am using a Samsung Galaxy S23 with One UI 6.0 (Android 14)

**Comment by vkryl** [comment]
What do you see in Hold app version — Push Services?

**Comment by 10Meisterbaelle** [comment]
Whete do I find that?Am 28.03.24, 02:56 schrieb Vyacheslav ***@***.***>:

   
  What do you see in Hold app version — Push Services? Also please include Copy report details from there.

**Comment by vkryl** [comment]
App settings - hold app version on the bottom.

**Comment by vkryl** [comment]
The only known notification reliability issue was fixed in 1706 build.
