### ISSUE TITLE
Enhancement of the lock settings: lock after closure of the app 

### ISSUE THREAD

**Issue by Moostek** [TGX-Android/Telegram-X#589]
Hello, I miss one crucial option in automatic lock settings of Telegram X app. It will be really nice to add there an option t**o lock the app automatically after I close Telegram X app**, i.e. I swipe the app out on the screen. Because even I restart the phone, the Telegram X app is open and does not call for the password. I believe that this option can perfectly complete the actual options and help to secure the app against other possible situations. 

Thank you!

**Comment by Sajilck** [comment]
You can enable app lock under
Settings > Privacy and Security > Passcode lock

To close the app instantly, choose **Auto-lock** as **Instant**

![Screenshot_20240402_042252_Telegram X](https://github.com/TGX-Android/Telegram-X/assets/25002879/8df15865-9131-4d16-9475-ed185e139f75)
