### ISSUE TITLE
some more #RTL issues

### ISSUE THREAD

**Issue by Aphotic** [TGX-Android/Telegram-X#594]
- [ ] [t.me/tgandroidtests/271218](https://t.me/tgandroidtests/271218) — incorrect ellipsis position in mixed-direction chat preview
- [ ] [t.me/tgandroidtests/271205](https://t.me/tgandroidtests/271205) / [expected behavior](https://t.me/tgandroidtests/271206) — incorrect RTL alignment for certain emojis
- [ ] [t.me/tgandroidtests/271219](https://t.me/tgandroidtests/271219) — RTL text alignment in chat list preview (minor)
- [ ] https://t.me/tgandroidtests/271298
- [ ] https://t.me/tgandroidtests/271415
- [ ] https://t.me/tgandroidtests/271427
- [ ] https://t.me/tgandroidtests/270764

Lets update this post with more that we find from the group to make it easier for devs

**Comment by vkryl** [comment]
Could you please update the list with the latest build (1720)? At least emoji should be okay now.
