### ISSUE TITLE
False-positive emulator detection warning on Redmi `22041216C`

### ISSUE THREAD

**Issue by 2240523471** [TGX-Android/Telegram-X#600]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: Redmi `22041216C`
Product: `22041216C`
Device: `22041216C`
Hardware: `22041216C`

**The app version I am using:**

Telegram X 0.26.7.1709-arm64-v8a (emulator) (8e310da0)
PRs: #595 (6827c0d4)
TDLib: 1.8.28 (tdlib/td@77b3479)
tgcalls: TGX-Android/tgcalls@6adef64
WebRTC: TGX-Android/webrtc@df2ed68b47
Android: 12L (32)
Device: Redmi Redmi 22041216C (V417IR release-keys)
Screen: 1600x900 (density: 1.5, fps: 60.000004)
Build: `OnePlus/OnePlus8Pro/OnePlus8Pro:12/V417IR/2404261855:user/release-keys`
Package: org.thunderdog.challegram
Locale: zh_CN (app: en)
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `0xb`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by vkryl** [comment]
Do you have any device connected to your phone?

**Comment by 2240523471** [comment]
yes发自我的 iPhone在 2024年5月7日，下午8:25，Vyacheslav ***@***.***> 写道：Do you have any device connected to your phone?

**Comment by 2240523471** [comment]
but I don't have any more phone numbers 发自我的 iPhone在 2024年5月7日，下午8:25，Vyacheslav ***@***.***> 写道：﻿
Do you have any device connected to your phone?

**Comment by vkryl** [comment]
If you use a real smartphone (not an emulator or similar software):

1. Disconnect any devices from your phone (for example, PC or laptop)
2. Restart Telegram X
3. Log in normally

**Comment by 2240523471** [comment]
but i mean is the telegram Prompt my mobile phone number is banned发自我的 iPhone在 2024年5月8日，下午6:06，Vyacheslav ***@***.***> 写道：﻿
If you use a real smartphone (not an emulator or similar software):

Disconnect any devices from your phone (for example, PC or laptop)
Restart Telegram X
Log in normally

**Comment by vkryl** [comment]
If your phone number is completely banned, please contact login@telegram.org and specify your phone number fully. This is the only way to get phone number unbanned that I am aware of.
