### ISSUE TITLE
Registration issue on Telegram X

### ISSUE THREAD

**Issue by nix0x00** [TGX-Android/Telegram-X#609]
As registration is not available on Telegram X, thus I was trying ti build it as we need this feature on our application. This is however available on Telegram.

Now, does `TDlib` provide registration functions or not at the moment? Can someone guide me in the right direction.

**Comment by vkryl** [comment]
You can create an account in Telegram X, and there are no noticeable issues according to stats.

If there is an issue you are able to reproduce, please collect tdlib log with DEBUG verbosity, log size up to 50MB, and send it to https://t.me/tdlib_bot.

Thank you.

**Comment by nix0x00** [comment]
> Can you also send your phone number to [login@telegram.org](mailto:login@telegram.org) with a link to this GitHub issue?

Sure @vkryl thank you so much for the quick replies.
