### ISSUE TITLE
Telegram&Telegram x login problem

### ISSUE THREAD

**Issue by sjhm131** [TGX-Android/Telegram-X#635]
I registered my Telegram account using my phone number, but a while ago, Telegram suddenly went offline. When I tried to log in again, I couldn't receive the verification code. I was previously using an iOS device. Even when I tried to log in using Telegram X on an Android phone, I still couldn't get the verification code.
How can i solve this?

**Comment by Sajilck** [comment]
If you are not receiving SMS codes, you can contact to login@telegram.org
