### ISSUE TITLE
Photos taken by the camera are overexposed 

### ISSUE THREAD

**Issue by pippo73** [TGX-Android/Telegram-X#668]
I'm running 02691730 on a pixel 7 pro with last lenageos rom

When I take photos with TGX all the picture are much overexposed.
If I do the same with the official TG app everything is OK.
![20240613_200428.jpg](https://github.com/TGX-Android/Telegram-X/assets/757121/a0490333-cb26-4bcf-ac2b-cbd9beb55f27)

This is a picture taken with TGX
![2024-06-13-20-15-46-705.jpg](https://github.com/TGX-Android/Telegram-X/assets/757121/81d14e54-b54a-4d38-9627-5e5c78b67562)

This is the same pic taken with the camera app.

How can I fix it?

**Comment by vkryl** [comment]
Try switching to `CameraX` in Settings — Interface — In-App Camera — Camera Type.

**Comment by vkryl** [comment]
Try switching to `CameraX` in Settings — Interface — In-App Camera — Camera Type.

**Comment by pippo73** [comment]
Thank you.
Changing from traditional to cameraX and to system, works! 😊
