### ISSUE TITLE
False-positive emulator detection warning on Xiaomi `2206123SC`

### ISSUE THREAD

**Issue by Boffuun** [TGX-Android/Telegram-X#684]
Hello. I use **Telegram X** on a real device, but it says I am running on an emulator.

**My real device details:**

Name: Xiaomi `2206123SC`
Product: `2206123SC`
Device: `2206123SC`
Hardware: `2206123SC`

**The app version I am using:**

Telegram X 0.26.9.1730-arm64-v8a (emulator) (7bc96dbf)
TDLib: 1.8.30 (tdlib/td@b102c3a)
tgcalls: TGX-Android/tgcalls@6adef64
WebRTC: TGX-Android/webrtc@df2ed68b47
Android: 12L (32)
Device: Xiaomi Xiaomi 2206123SC (V417IR release-keys)
Screen: 960x540 (density: 1.375, fps: 60.000004)
Build: `OnePlus/OnePlus8Pro/OnePlus8Pro:12/V417IR/2406211805:user/release-keys`
Package: org.thunderdog.challegram
Locale: zh_CN (app: en)
APK Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

**Emulator detection result:** `0xb`

Please take a look if this warning can be resolved for my device.
Thank you!

**Comment by Avaladirva** [comment]
> Здравствуйте. Я использую **Telegram X** на реальном устройстве, но он говорит, что я работаю на эмуляторе.
> 
> **Данные моего реального устройства:**
> 
> Имя: Xiaomi `2206123SC` Продукт: `2206123SC` Устройство: `2206123SC` Аппаратное обеспечение:`2206123SC`
> 
> **Версия приложения, которую я использую:**
> 
> Telegram X 0.26.9.1730-arm64-v8a (эмулятор) ( [7bc96db](https://github.com/TGX-Android/Telegram-X/commit/7bc96dbf0fadfab1625a0ec0acfaf4c0d52751fb) ) TDLib: 1.8.30 ( [tdlib/td@ b102c3a](https://github.com/tdlib/td/commit/b102c3a) ) tgcalls: [TGX-Android/tgcalls@ 6adef64](https://github.com/TGX-Android/tgcalls/commit/6adef64) WebRTC: [TGX-Android/webrtc@ df2ed68b47](https://github.com/TGX-Android/webrtc/commit/df2ed68b47) Android: 12L (32) Устройство: Xiaomi Xiaomi 2206123SC (V417IR release-keys) Экран: 960x540 (плотность: 1,375, fps: 60,000004) Сборка: `OnePlus/OnePlus8Pro/OnePlus8Pro:12/V417IR/2406211805:user/release-keys` Пакет: org.thunderdog.challegram Язык: zh_CN (приложение: en) APK Fingerprint:`66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`
> 
> **Результат обнаружения эмулятора:** `0xb`
> 
> Пожалуйста, посмотрите, можно ли устранить это предупреждение для моего устройства. Спасибо!

Vcb
