### ISSUE TITLE
When I register an account, everyone who has added my number finds out about it without my consent.

### ISSUE THREAD

**Issue by rakakarakaka** [TGX-Android/Telegram-X#698]
Sorry I don't know English language.

The issue is as follows: when I register my account through Telegram X and **do not grant access to contacts**, everyone who has added my number to their phone book sees a message in Telegram X saying 'Hooray, your contact has joined Telegram, wow, how cool!"

I want to be able to register an account without anyone receiving a message that I have registered.

**Comment by rakakarakaka** [comment]
@vkryl @Sajilck  you can fix it?

**Comment by RememberTheAir** [comment]
it's a server-side thing, clients can't fix that. that notification is not a request sent by the client, it's sent directly by the server

**Comment by rakakarakaka** [comment]
> it's a server-side thing, clients can't fix that. that notification is not a request sent by the client, it's sent directly by the server

But If client not has access to my contacts? (like I not added this peoples to contacts)

**Comment by RememberTheAir** [comment]
It depends on the people who have your number in _their_ contacts. Telegram knows their phonebook and thus is aware that you are saved there, and notifies the user when you sign up

**Comment by rakakarakaka** [comment]
> It depends on the people who have your number in _their_ contacts. Telegram knows their phonebook and thus is aware that you are saved there, and notifies the user when you sign up

But I have not added these people to my phone book, and I do not want them to see that I am registering because they are unknown peoples who shouldn't know that I registered.

**Comment by RememberTheAir** [comment]
it's not about _your _phonebook_, it's about _their _phonebook_. These people have added your phone number to their contacts, so they supposedly know you (or think they do). Regardless, they can just open their telegram contacts and see your account there. I think there must be an option to turn it off too, but that's something that is out of the scope of a client, because as I said everything is handled by the server

**Comment by Sajilck** [comment]
Are you using the latest version of Telegram-X? Because it registers new account silently and will not produce any notifications.  If it still does, it's a server side bug

**Comment by rakakarakaka** [comment]
> Are you using the latest version of Telegram-X? Because it registers new account silently and will not produce any notifications. If it still does, it's a server side bug

Yes. And Telegram-X with No access to my phonebook.

How to report server side bug ?

**Comment by Sajilck** [comment]
bugs.telegram.org

**Comment by rakakarakaka** [comment]
> bugs.telegram.org

@Sajilck
They remove all my bug reports ("Admin Dog")

**Comment by Sajilck** [comment]
There might be a reason it gets removed like it is duplicate or without proper details. Create a proper report

**Comment by rakakarakaka** [comment]
@Sajilck I create a bug report "Confidentiality Violation Critical Error", Admin Dog deletes my bug report for no reason (not closed, just deleted).

**Comment by Sajilck** [comment]
Closing the issue as this is not a Telegram-X bug, tracking the issue here
https://bugs.telegram.org/c/41960
